#!/usr/bin/env zsh
# shellcheck disable=SC1090
set -e

local LATEST_NODE_LTS_VERSION="20.12.0"

local CONFIG_DIR=~/.oroshi/config/_languages/javascript/nvm
local DEST_DIR=~/.nvm

# Installing nvm if not installed
if [[ ! -d $DEST_DIR ]]; then
	git-directory-sync \
		git@github.com:creationix/nvm.git \
		$DEST_DIR

	ln -fs \
		$CONFIG_DIR/default-packages \
		$DEST_DIR

	echo "Now, start a new zsh session and re-run this script"
fi

# Installing node
export NVM_DIR=$DEST_DIR
source $NVM_DIR/nvm.sh
nvm install $LATEST_NODE_LTS_VERSION --no-nvmrc
