#!/usr/bin/env bash
set -e

# Utilities
~/.oroshi/scripts/install/music/sox

# Formats
~/.oroshi/scripts/install/music/aac
~/.oroshi/scripts/install/music/flac
~/.oroshi/scripts/install/music/mp3
~/.oroshi/scripts/install/music/ogg

# Players
~/.oroshi/scripts/install/music/cmus
~/.oroshi/scripts/install/music/mplayer
