#!/usr/bin/env zsh
# ImageMagick config
# Default ImageMagick config has low default values for memory management,
# making it fail when converting large files
# We are using a custom policy that should fix it
set -e

CONFIG_DIR="${0:h:a}/config"
LOCAL_CONFIG_DIR=~/.config/ImageMagick

mkdir -p $LOCAL_CONFIG_DIR
ln -fs $CONFIG_DIR/policy.xml $LOCAL_CONFIG_DIR/policy.xml
