#!/usr/bin/env zsh
# Image Magick: Convert to and from all image formats
set -e

# Ubuntu 24.04 ships with ImageMagick 6
# ImageMagick 7 is available as a single binary
# It replaces the old `convert` method, and all other methods should use this as
# its primary entrypoint

local VERSION="7.1.2-30"
local DOWNLOAD_DIR=~/local/etc/magick
local DOWNLOAD_URL="https://github.com/ImageMagick/ImageMagick/releases/download/${VERSION}/ImageMagick-${VERSION}-gcc-x86_64.AppImage"

# Dependencies needed
sudo apt install libfuse2t64

# Download the binary
mkdir -p $DOWNLOAD_DIR
cd $DOWNLOAD_DIR
rm -rf ./magick
echo "Downloading ImageMagick ${VERSION}..."
wget $DOWNLOAD_URL -O ./magick
chmod +x ./magick

# Create links
cd ~/local/bin
ln -fs ./../etc/magick/magick ./magick

"${0:h}/deploy"
