#!/usr/bin/env bash
# Google Cloud CLI (gcloud)
# https://cloud.google.com/sdk/docs/install-sdk
set -e

# Install required packages
sudo apt-get install \
  apt-transport-https \
  ca-certificates gnupg

# Add the Google Cloud public key
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg |
  sudo tee /usr/share/keyrings/cloud.google.gpg

# Add the gcloud CLI distribution URI
echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" |
  sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list

# Update and install
sudo apt-get update
sudo apt-get install google-cloud-cli
