#!/usr/bin/env bash

# Installing git from source
cd ~/local/etc
git clone https://github.com/git/git.git
cd ./git

# Installing dependencies
sudo apt-get install \
  libcurl4-gnutls-dev \
  libexpat1-dev \
  gettext \
  libz-dev \
  libssl-dev \
  asciidoc \
  xmlto \
  docbook2x

# Compiling
make prefix=/home/$USER/local all doc info
sudo make prefix=/home/$USER/local install install-doc install-html install-info


# Installing git-extras
# Install can warn about being unable to delete a bash-completion, but
# everything is still installed
cd ~/local/etc
git clone git@github.com:tj/git-extras.git
cd ./git-extras

gem install ronn
PREFIX=~/local make
PREFIX=~/local make install

# Installing tig
cd ~/local/src
git clone git@github.com:jonas/tig.git
cd ./tig
make prefix=/home/$USER/local
make install prefix=/home/$USER/local
