#!/usr/bin/env zsh

echo "Downloading source from github"
cd ~/local/etc
git clone --recursive git://github.com/nvie/gitflow.git

echo "Creating symlinks"
cd ~/local/bin/
for i in ~/local/etc/gitflow/git*; do
	ln -s ../etc/gitflow/${i:t} .
done

