#!/usr/bin/env bash

# On Ubuntu 13.10 git subtree is installed, but is not linked to the default
# git commands.
sudo chmod +x /usr/share/doc/git/contrib/subtree/git-subtree.sh
sudo ln -s /usr/share/doc/git/contrib/subtree/git-subtree.sh /usr/lib/git-core/git-subtree
