#!/usr/bin/env zsh
# Scribd-dl: Download from scribd.com and slideshare.net
# https://github.com/rkwyu/scribd-dl
set -e

# Clone latest copy
cd ~/local/src
git-directory-sync git@github.com:rkwyu/scribd-dl.git

# Install deps
cd ./scribd-dl
yarn install
