#!/usr/bin/env zsh
# Configure custom global keybinding
# Those open specific applications when pressed

local                  shortcuts=(
  # Name                 Binding           Command
  "Calculator"           "Insert"          "gnome-calculator"
  "Chrome"               "<Super>C"        "google-chrome"
  "Firefox"              "<Super>F"        "firefox"
  "Slack"                "<Super>S"        "slack"
  "Kitty"                "<Super>T"        "/home/tim/.oroshi/scripts/bin/kitty/kitty-restore"
  "Keepass"              "<Super>K"        "/home/tim/.oroshi/scripts/bin/better-keepass /home/tim/perso/Dropbox/tim/keys.kdbx"
  "Spotify Pause"        "<Super>I"        "/home/tim/.oroshi/scripts/bin/spotify/spotify"
  "Spotify Next"         "<Super>L"        "/home/tim/.oroshi/scripts/bin/spotify/spotify-next"
  "Spotify Previous"     "<Super>H"        "/home/tim/.oroshi/scripts/bin/spotify/spotify-previous"
  "Flameshot"            "Print"           "script --command \"flameshot gui\" /dev/null"     # Flameshot need to be called in a fork when called from a keybinding
  # "Peek"                 "/home/tim/.oroshi/scripts/bin/peek"                  "<Super><Alt>Print"

)

local GSETTINGS_ROOT="org.gnome.settings-daemon.plugins.media-keys.custom-keybinding"
local GSETTINGS_DIRECTORY="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"

function setKeybinding() {
  local bindingPath=$1
  local bindingKey=$2
  local bindingValue=$3
  gsettings set "$bindingPath" "$bindingKey" "$bindingValue"
}

# Iterating through all the bindings
local shortcut_count=$((${#shortcuts[@]} / 3))
local shortcut_inventory=()
for shortcut_index in {1..$shortcut_count}; do
  local custom_index=$((shortcut_index - 1))
  local array_index=$((1 + $custom_index * 3))

  local shortcut_name=$shortcuts[$array_index]
  local shortcut_binding=$shortcuts[$array_index+1]
  local shortcut_command=$shortcuts[$array_index+2]

  # Setting each shortcut individually
  setKeybinding "${GSETTINGS_ROOT}:${GSETTINGS_DIRECTORY}/custom${custom_index}/" "name" "'${shortcut_name}'"
  setKeybinding "${GSETTINGS_ROOT}:${GSETTINGS_DIRECTORY}/custom${custom_index}/" "binding" "'${shortcut_binding}'"
  setKeybinding "${GSETTINGS_ROOT}:${GSETTINGS_DIRECTORY}/custom${custom_index}/" "command" "'${shortcut_command}'"

  shortcut_inventory+=("'${GSETTINGS_DIRECTORY}/custom${custom_index}/'")
done

setKeybinding "org.gnome.settings-daemon.plugins.media-keys" "custom-keybindings" "[${(j:,:)shortcut_inventory}]"
