#!/usr/bin/env zsh
# Keybindings to interact with windows

# Alt-Tab {{{
# [Alt-Tab] Switch through windows in one workspace at a time
dconf write /org/gnome/shell/extensions/advanced-alt-tab-window-switcher/switcher-popup-position 2
dconf write /org/gnome/shell/extensions/advanced-alt-tab-window-switcher/switcher-popup-preview-selected 1
dconf write /org/gnome/shell/extensions/advanced-alt-tab-window-switcher/switcher-popup-tooltip-title 3
dconf write /org/gnome/shell/extensions/advanced-alt-tab-window-switcher/switcher-popup-start-search false
dconf write /org/gnome/shell/extensions/advanced-alt-tab-window-switcher/switcher-popup-show-if-no-win false
dconf write /org/gnome/shell/extensions/advanced-alt-tab-window-switcher/switcher-popup-second-tab-switch-filter false
dconf write /org/gnome/shell/extensions/advanced-alt-tab-window-switcher/win-switcher-popup-filter 2
dconf write /org/gnome/shell/extensions/advanced-alt-tab-window-switcher/win-switcher-popup-preview-size 256
dconf write /org/gnome/shell/extensions/advanced-alt-tab-window-switcher/win-switcher-popup-ws-indexes false
dconf write /org/gnome/shell/extensions/advanced-alt-tab-window-switcher/win-switcher-popup-titles 2
dconf write /org/gnome/shell/extensions/advanced-alt-tab-window-switcher/win-switcher-popup-icon-size 0

dconf write /org/gnome/desktop/wm/keybindings/switch-windows "['<Alt>Tab']"
# }}}

# 
dconf write /org/gnome/shell/extensions/tiling-assistant/enable-tiling-popup false
dconf write /org/gnome/shell/extensions/tiling-assistant/tile-maximize "['<Super>Up']"
dconf write /org/gnome/shell/extensions/tiling-assistant/restore-window "['<Super>Down']"
dconf write /org/gnome/shell/extensions/tiling-assistant/tile-right-half "['<Super>Right','<Super><Alt>Right']"
dconf write /org/gnome/shell/extensions/tiling-assistant/tile-left-half "['<Super>Left','<Super><Alt>Left']"
dconf write /org/gnome/shell/extensions/tiling-assistant/tile-top-half "['<Super><Alt>Up']"
dconf write /org/gnome/shell/extensions/tiling-assistant/tile-bottom-half "['<Super><Alt>Down']"

