#!/usr/bin/env zsh

# Paths
local destFile=~/.xbindkeysrc
local configDir=~/.oroshi/config/xbindkeys
local defaultFile=${configDir}/xbindkeysrc.conf
local localFile=${configDir}/local/${HOST}.conf

# Kill previous bindings
killall xbindkeys &>/dev/null

# Create a ~/.xbindkeysrc
cat $defaultFile > $destFile

# Add custom bindings for this machine, if any
if [[ -r $localFile ]]; then
  cat ${localFile} >> $destFile
fi

# Reload config
xbindkeys --poll-rc
