#!/usr/bin/env bash

echo "Installing jshint"
npm install -g jshint

echo "Installing eslint"
npm install -g eslint
npm install -g eslint-plugin-react
npm install -g eslint-config-airbnb
npm install -g eslint-config-algolia
npm install -g babel-eslint

echo "Installing jscs"
npm install -g jscs

echo "Installing jsmin/uglifyjs"
npm install -g uglify-js

echo "Installing jsbeautify"
npm install -g js-beautify



