#!/usr/bin/env bash
# jq, a json parser

echo "Downloading source"
cd ~/local/src
wget http://stedolan.github.com/jq/download/source/jq.tgz

echo "Extracting"
extract jq.tgz

echo "Compiling"
cd ./jq
make

echo "Moving binary"
mv ./jq ~/local/bin/jq

