#!/usr/bin/env bash
set -ex

sudo apt-get install virtualbox

# Kubectl
cd ~/local/bin
wget \
  https://storage.googleapis.com/kubernetes-release/release/v1.10.0/bin/linux/amd64/kubectl \
  -O kubectl
chmod +x ./kubectl

# Minikube
cd ~/local/bin
wget \
  https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
  -O minikube
chmod +x ./minikube
