#!/usr/bin/env bash
# Nodejs

#Installing dependencies
sudo apt-get install build-essential
sudo apt-get install libssl-dev

echo "Installing nvm"
cd ~/local/etc
git clone https://github.com/creationix/nvm.git ./nvm

cd ./nvm
source ./nvm.sh
nvm install 0.10
nvm use 0.10
nvm alias default 0.10
