#!/usr/bin/env bash

# Both python 2 and python 3 system wide
sudo apt-get install python-pip python3-pip

# pyenv to handle global virtualenvs
curl \
  -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer \
  | bash

# Install python versions using pyenv
pyenv install 3.7.0
pyenv install 2.7.15

# Create virtual envs
pyenv virtualenv 3.7.0 3
pyenv virtualenv 2.7.15 2

# Check for binaries in python 3, then 2, then system wide
pyenv global 3 2 system

# pipenv to handle local environment per project
pip install pipenv

# Linter
sudo apt-get install pylint
pip install autopep8
