#!/usr/bin/env bash

sudo apt-get install \
    build-essential \
    curl \
    git \
    libbz2-dev \
    libncurses5-dev \
    libreadline-dev \
    libsqlite3-dev \
    libssl-dev \
    llvm \
    wget \
    zlib1g-dev

# We first install pyenv to load the various python env, to easily switch
# between 2 and 3
curl \
  -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer \
  | bash

# Reload pyenv in the shell
source ~/.zshrc


# sudo apt-get install python-pip

# pip install --upgrade pip
# pip install --user pipenv
