#!/usr/bin/env bash

echo "Installing python dev"
sudo apt-get install python-dev
sudo apt-get install python-setuptools

echo "Installing pip"
sudo apt-get install python-pip
pip install --upgrade pip

echo "Installing flake8 to check and lint code"
pip install flake8
