#!/usr/bin/env bash
# HTML5 version of HtmlTidy
cd ~/local/src/
git clone git@github.com:htacg/tidy-html5.git

cd ./tidy-html5/build/cmake
cmake ../.. -DCMAKE_INSTALL_PREFIX=/home/tim/local/
make
make install
