#!/usr/bin/env sh
gsettings set org.compiz.integrated command-1 "'terminator'"
gsettings set org.compiz.integrated command-2 "'chromium-browser --profile-directory=\"Profile 1\"'"
gsettings set org.compiz.integrated command-3 "'chromium-browser --profile-directory=\"Profile 2\"'"
gsettings set org.compiz.integrated command-4 "'keepassx ~/Dropbox/perso/config/keys.kdb'"
gsettings set org.compiz.integrated command-5 "'chromium-browser --profile-directory=\"Profile 3\"'"
gsettings set org.compiz.integrated command-6 "'tomate'"
gsettings set org.compiz.integrated command-7 "''"
gsettings set org.compiz.integrated command-8 "''"
gsettings set org.compiz.integrated command-9 "''"
gsettings set org.compiz.integrated command-10 "''"
gsettings set org.compiz.integrated command-11 "''"
gsettings set org.compiz.integrated command-12 "''"
gsettings set org.compiz.integrated command-21 "'/usr/bin/gnome-system-monitor -p'"
gsettings set org.compiz.integrated command-screenshot "'gnome-screenshot'"
gsettings set org.compiz.integrated command-window-screenshot "'gnome-screenshot --window'"
gsettings set org.compiz.integrated display-all-workspaces "true"
gsettings set org.compiz.integrated run-command-1 "['<Super>t']"
gsettings set org.compiz.integrated run-command-2 "['<Control><Super>C']"
gsettings set org.compiz.integrated run-command-3 "['<Control><Super><Alt>C']"
gsettings set org.compiz.integrated run-command-4 "['<Control><Super>K']"
gsettings set org.compiz.integrated run-command-5 "['<Super><Alt>C']"
gsettings set org.compiz.integrated run-command-6 "['<Control><Super>P']"
gsettings set org.compiz.integrated run-command-7 "['disabled']"
gsettings set org.compiz.integrated run-command-8 "['disabled']"
gsettings set org.compiz.integrated run-command-9 "['disabled']"
gsettings set org.compiz.integrated run-command-10 "['disabled']"
gsettings set org.compiz.integrated run-command-11 "['disabled']"
gsettings set org.compiz.integrated run-command-12 "['disabled']"
gsettings set org.compiz.integrated run-command-21 "['<Control><Alt>Delete']"
gsettings set org.compiz.integrated show-hud "['disabled']"
