#!/usr/bin/env bash
# Kitty: The fast, feature-rich, GPU based terminal emulator
# https://sw.kovidgoyal.net/kitty/
set -e

# Download and extract
# Kitty releases are coming often and the Ubuntu source files are usually too
# old to reflect the current documentation. Better to grab it from the GitHub
# nighthly releases.
DOWNLOAD_URL="https://github.com/kovidgoyal/kitty/releases/download/nightly/kitty-nightly-x86_64.txz"

INSTALL_DIR=~/local/etc/kitty
rm -rf $INSTALL_DIR
mkdir -p $INSTALL_DIR
cd $INSTALL_DIR

wget $DOWNLOAD_URL -O kitty.txz
tar Jxvf kitty.txz
rm kitty.txz

cd ~/local/bin
ln -fs ../etc/kitty/bin/kitty ./kitty

# Prevents "WARNING: terminal is not fully functional" warnings when using
# sudo systemctl status
# See: https://github.com/kovidgoyal/kitty/issues/1567
sudo apt-get install kitty-terminfo
