#!/usr/bin/env bash
set -ex

# Instructions as per
# https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository

# Remove old installs
sudo apt-get remove docker docker.io

# Setting system up to date
sudo apt-get update

# Allow using repo over HTTPS
sudo apt-get install \
    ca-certificates \
    curl

# Use Docker key
sudo mkdir -m 0755 -p /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc

# Add official repo
# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update

# Setting system up to date again
sudo apt-get update

# Actually installing docker
sudo apt-get install \
  docker-ce \
  docker-ce-cli \
  containerd.io \
  docker-buildx-plugin \
  docker-compose-plugin

# Verify it works
sudo docker run hello-world

# Start docker on boot
sudo systemctl enable docker

echo "You should log out and back in for this to work"
