#!/usr/bin/env zsh
# Dockerfile linter
# https://github.com/hadolint/hadolint
set -e
DOWNLOAD_URL="https://github.com/hadolint/hadolint/releases/download/v2.5.0/hadolint-Linux-x86_64"

cd ~/local/bin
wget "$DOWNLOAD_URL" -O hadolint
chmod +x hadolint
