#!/usr/bin/env zsh
# Regenerate ./dist/oroshi.tmTheme from ./src/oroshi.xml
set -e

local currentDir=${0:a:h}

mkdir -p $currentDir/dist

colors-template-render \
  $currentDir/src/oroshi.xml \
  >$currentDir/dist/oroshi.tmTheme

bat cache --build 1>/dev/null
