#!/usr/bin/env zsh
# Regenerate ./dist/oroshi.tmTheme from ./src/oroshi.xml
set -e

source $OROSHI_ROOT/tools/term/zsh/config/theming/env/colors.zsh

local currentDir=${0:a:h}

mkdir -p $currentDir/dist

envsubst \
	<${currentDir}/src/oroshi.xml \
	>${currentDir}/dist/oroshi.tmTheme

bat cache --build 1>/dev/null
