#!/usr/bin/env bash
set -e

sudo apt-get install zsh

# Install additional completions
mkdir -p ~/local/src
cd ~/local/src

git clone git@github.com:zsh-users/zsh-completions.git
git clone git@github.com:zsh-users/zsh-syntax-highlighting.git

echo "--------------"
echo "You should manually edit /etc/passwd to add /usr/bin/zsh as your shell"
echo "You should now reboot for the shell change to take effect correctly."
echo "--------------"

"$(dirname "$0")/deploy"
