#!/usr/bin/env zsh
# Algolia CLI
set -ex

local DOWNLOAD_URL="https://github.com/algolia/cli/releases/download/v1.3.6/algolia_1.3.6_linux_386.deb"
local LOCAL_FILE="algolia.deb"

# Download
cd ~/local/tmp
wget $DOWNLOAD_URL -O $LOCAL_FILE

# Install
sudo dpkg -i $LOCAL_FILE
sudo apt-get -f install
rm $LOCAL_FILE
