#!/usr/bin/env sh
set -e

cd ~/local/tmp
wget \
  "https://github.com/sharkdp/bat/releases/download/v0.16.0/bat_0.16.0_amd64.deb" \
  -O bat.deb

sudo dpkg -i bat.deb
sudo apt-get -f install
rm ~/local/tmp/bat.deb
