#!/usr/bin/env sh
# Better cat, with syntax highlight
# https://github.com/sharkdp/bat
set -e

DOWNLOAD_URL="https://github.com/sharkdp/bat/releases/download/v0.22.1/bat_0.22.1_amd64.deb"
cd ~/local/tmp
wget $DOWNLOAD_URL -O bat.deb
sudo dpkg -i ./bat.deb
sudo apt-get -f install

# Also install bat-extras for more goodness
# https://github.com/eth-p/bat-extras
# https://github.com/eth-p/bat-extras/blob/master/doc/batman.md
# https://github.com/eth-p/bat-extras/blob/master/doc/batpipe.md
# https://github.com/eth-p/bat-extras/blob/master/doc/batwatch.md
# https://github.com/eth-p/bat-extras/blob/master/doc/batdiff.md
# https://github.com/eth-p/bat-extras/blob/master/doc/prettybat.md
cd ~/local/etc
git clone git@github.com:eth-p/bat-extras.git
ln -fs ~/local/etc/bat-extras/src/batdiff.sh ~/local/bin/batdiff
ln -fs ~/local/etc/bat-extras/src/batman.sh ~/local/bin/batman
ln -fs ~/local/etc/bat-extras/src/batpipe.sh ~/local/bin/batpipe
ln -fs ~/local/etc/bat-extras/src/batwatch.sh ~/local/bin/batwatch
ln -fs ~/local/etc/bat-extras/src/prettybat.sh ~/local/bin/prettybat
