#!/usr/bin/env bash
# Testing framework for Phantomjs

cd /usr/local/etc
git clone git://github.com/n1k0/casperjs.git

cd casperjs
git checkout tags/1.0.0-RC3

cd /usr/local/bin
ln -s ../etc/casperjs/bin/casperjs

