#!/usr/bin/env bash

echo "Creating ~/local"
mkdir -p ~/local

echo "Symlinkin dirs from /usr/local to ~/local"
for i in  ~/local//usr/local/*; do
	mv -u /usr/local/$i ~/local/$i
	ln -s ~/local/$i /usr/local/$i
done

echo "Add others useful local directories"
mkdir -p ~/local/mnt
mkdir -p ~/local/tmp

