#!/usr/bin/env bash

echo "Creating ~/local"
mkdir -p ~/local

echo "Symlinking dirs from /usr/local to ~/local"
for i in /usr/local/*/; do
  echo `basename $i`
	sudo mv -u $i ~/local/`basename $i`
  ln -s ~/local/`basename $i` $i
done

echo "Add others useful local directories"
mkdir -p ~/local/mnt
mkdir -p ~/local/tmp

