#!/usr/bin/env bash
set -e

# Instructions as per
# https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository

# Remove old installs
sudo apt-get remove docker docker.io

# Setting system up to date
sudo apt-get update

# Allow using repo over HTTPS
sudo apt-get install \
    ca-certificates \
    curl \
    gnupg

# Use Docker key
sudo mkdir -m 0755 -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

# Add official repo
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Setting system up to date again
sudo apt-get update

# Actually installing docker
sudo apt-get install docker-ce docker-ce-cli containerd.io

# Add current user to the docker group
sudo usermod -aG docker "$USER"

# Start docker on bood
sudo systemctl enable docker

echo "You should log out and back in for this to work"

