#!/usr/bin/env zsh
set -e

# dry is an alternative Docker CLI to list all containers and images,
# stop/start/delete them

DOWNLOAD_URL="https://github.com/moncho/dry/releases/download/v0.11.1/dry-linux-386"

cd ~/local/bin
wget $DOWNLOAD_URL -O dry

chmod +x ./dry
