#!/usr/bin/env bash

mkdir -p ~/local/src/calibre

wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py \
  | python -c "import sys; main=lambda x,y:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main('~/local/src', True)"

ln -fs ~/local/src/calibre/calibre ~/local/bin/
ln -fs ~/local/src/calibre/ebook-convert ~/local/bin/
ln -fs ~/local/src/calibre/ebook-meta ~/local/bin/
ln -fs ~/local/src/calibre/ebook-viewer ~/local/bin/
