#!/usr/bin/env zsh
# Run arbitrary commands when file change

# Download
cd ~/local/src
git clone git@github.com:eradman/entr.git

# Install
cd ./entr
./configure
CFLAGS="-static" make test
PREFIX=$HOME/local make install
