#!/usr/bin/env bash
set -ex

mkdir -p ~/local/tmp/exa
cd ~/local/tmp/exa

wget \
  https://github.com/ogham/exa/releases/download/v0.10.0/exa-linux-x86_64-v0.10.0.zip \
  -O exa.zip
unzip -o exa.zip
mv ./bin/exa ~/local/bin/exa
