#!/usr/bin/env bash
cd /usr/local/src
git clone git://github.com/clvv/fasd.git
cd ./fasd
mkdir /usr/local/etc/fasd
PREFIX=/usr/local/etc/fasd make install
cd /usr/local/bin
ln -s ../etc/fasd/bin/fasd

