#!/usr/bin/env bash

echo "Cloning from github"
cd ~/local/src
git clone git://github.com/clvv/fasd.git

echo "Compiling"
cd ./fasd
mkdir -p ~/local/etc/fasd
PREFIX=~/local/etc/fasd make install

echo "Creating symlink"
cd ~/local/bin
ln -s ../etc/fasd/bin/fasd

