#!/usr/bin/env sh
set -e

cd ~/local/tmp
wget \
  "https://github.com/sharkdp/fd/releases/download/v8.1.1/fd_8.1.1_amd64.deb" \
  -O fd.deb

sudo dpkg -i fd.deb
sudo apt-get -f install
rm ~/local/tmp/fd.deb
