#!/usr/bin/env bash
# Download and manually compile ffmpeg to use proprietary codecs

echo "Download all dependencies"
sudo apt-get -y install \
	yasm \
	libfaac-dev \
	libmp3lame-dev \
	libopencore-amrnb-dev \
	libopencore-amrwb-dev \
	libtheora-dev \
	libvorbis-dev \
	libvpx-dev \
	libx264-dev \
	libxvidcore-dev

echo "Download svn source"
cd ~/local/etc
svn checkout svn://svn.ffmpeg.org/ffmpeg/trunk ffmpeg

echo "Configure"
cd ./ffmpeg
./configure	--enable-gpl \
	--enable-version3 \
	--enable-nonfree \
	--enable-postproc \
	--enable-libfaac \
	--enable-libmp3lame \
	--enable-libopencore-amrnb \
	--enable-libopencore-amrwb \
	--enable-libtheora \
	--enable-libvorbis \
	--enable-libvpx \
	--enable-libx264 \
	--enable-libxvid \
	--enable-x11grab

echo "Make"
make

echo "Create symlinks"
cd ~/local/bin/
ln -s ../etc/ffmpeg/ffmpeg .
