#!/usr/bin/env bash
# Note: On some Ubuntu versions, ffmpeg might not really be ffmeg
# http://stackoverflow.com/questions/9477115/what-are-the-differences-and-similarities-between-ffmpeg-libav-and-avconv/9477756#9477756

sudo apt-get install ffmpeg
