#!/usr/bin/env bash
sudo apt-get install msttcorefonts


mkdir -p ~/.fonts
cp ~/.oroshi/config/fonts/DejaVuSansMono/*.ttf ~/.fonts 
cp ~/.oroshi/config/fonts/Nerd.ttf ~/.fonts 
# cp ~/.oroshi/private/config/fonts/*.ttf ~/.fonts

fc-cache -f
