#!/usr/bin/env bash

# Installing git from source
cd ~/local/etc
git clone https://github.com/git/git.git
cd ./git

# Installing dependencies
sudo apt-get install \
  libcurl4-gnutls-dev \
  libexpat1-dev \
  gettext \
  libz-dev \
  libssl-dev \
  asciidoc \
  xmlto \
  docbook2x

# Compiling
make prefix="/home/$USER/local" all doc info
sudo make prefix="/home/$USER/local" install install-doc install-html install-info
