#!/usr/bin/env zsh

echo "Downloading source from github"
cd /usr/local/etc
git clone --recursive git://github.com/nvie/gitflow.git

echo "Creating symlinks"
cd /usr/local/bin/
for i in /usr/local/etc/gitflow/git*; do
	ln -s ../etc/gitflow/${i:t} .
done

