#!/usr/bin/env zsh
set -e

# Install gvm, no manage go versions
bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
source ~/.gvm/scripts/gvm

# Install dependencies
sudo apt-get install \
  bison

local LATEST_VERSION="go1.19.4"

# Now installing latest
gvm install $LATEST_VERSION -B
gvm use $LATEST_VERSION --default
