#!/usr/bin/zsh
# Tools for dealing with hardware stuff

# xsltproc        : Processor bit used by make
sudo apt-get install xsltproc

# boot-repair       : For when your boot fails
sudo add-apt-repository ppa:yannubuntu/boot-repair
sudo apt-get install -y boot-repair
# gparted         : For formating and partitioning
sudo apt-get install gparted
# xfsprogs        : To format in XFS
sudo apt-get install xfsprogs
# mtpfs           : To access mp3 players in MTP format
sudo apt-get install mtpfs mtp-tools
# fuse-exfat      : To be able to mount exFAT
sudo apt-add-repository ppa:relan/exfat
sudo apt-get install fuse-exfat

# bchunk          : For converting bin/cue to iso
sudo apt-get install bchunk
# nrg2iso         : For converting nrg files to iso
sudo apt-get install nrg2iso


