#!/usr/bin/zsh
# Tools used to read, parse and deal with HTML

# lynx          : textual browser, used to convert html2text
sudo apt-get install lynx

# readability   : To convert a webpage to a more readable version
cd ~/local/etc/
git clone https://github.com/gfxmonk/python-readability.git
cd ~/local/bin/
ln -s ../etc/python-readability/readability/readability.py readability

# tidy          : HTMLTidy
cd ~/local/etc/
git clone https://github.com/w3c/tidy-html5.git
sudo apt-get install xsltptroc
make -C build/gmake
sudo make install -C build/gmake

# chromium-browser  : Fast browsing
sudo apt-get install chromium-browser
