#!/usr/bin/env zsh

# https://keybase.io/docs/the_app/install_linux
wget https://prerelease.keybase.io/keybase_amd64.deb -O /tmp/keybase.deb
sudo dpkg -i /tmp/keybase.deb
sudo apt-get install -f
run_keybase
