#!/usr/bin/env bash
set -e

# Lint markdown
gem install mdl

# Cleanup markdown
cd ~/local/etc/
git clone https://github.com/drbunsen/formd.git
cd ~/local/bin
ln -s ../etc/formd/formd .

# Preview markdown
yarn global add @pixelastic/markdown-preview

# Clean markdown through yarn packages
yarn add global textlint \
                prettier \
                remark-cli \
                remark-lint 
echo "Also run yarn install from the root of ~/.oroshi"
