#!/usr/bin/env bash
# Installing nginx, fast webserver

echo "Installing dependencies"
sudo apt-get install libpcre3 libpcre3-dev


echo "Download nginx"
cd /usr/local/src
wget http://nginx.org/download/nginx-1.2.4.tar.gz

echo "Extracting"
extract nginx-1.2.4.tar.gz

echo "Configuring"
cd ./nginx-1.2.4
mkdir /usr/local/etc/nginx
./configure \
	--prefix=/usr/local/etc/nginx \
	--sbin-path=/usr/local/bin/nginx \
	--with-http_ssl_module

echo "Compiling"
make
sudo make instal
