#!/usr/bin/env bash
# shellcheck disable=SC1090
set -e

if [[ ! -d ~/.nvm ]]; then
  echo "Installing nvm"
  git clone git@github.com:creationix/nvm.git ~/.nvm
  source ~/.nvm/nvm.sh
  nvm install 14.13.0
fi

echo "Installing yarn to replace npm"
curl -o- -L https://yarnpkg.com/install.sh | bash

yarn global add emma-cli
yarn global add eslint_d
yarn global add prettier
