#!/usr/bin/env bash
# To extract pdf to images
sudo apt-get install xpdf

# To extract pages from pdf
sudo apt install pdftk

# Includes pdfcrop (also adds margins)
sudo apt-get install texlive-extra-utils

# To sign pdf
sudo apt-get install xournal

