#!/usr/bin/env bash
# Headless webkit browser

cd /usr/local/src/
wget \
	http://phantomjs.googlecode.com/files/phantomjs-1.7.0-linux-i686.tar.bz2
	-O phantomjs.tar.bz2

cp ./phantomjs.tar.bz2 ../etc/
cd /usr/local/etc

extract phantomjs.tar.bz2
mv phantomjs-1.7.0 phantomjs
rm phantomjs.tar.bz2

cd /usr/local/bin
ln -s ../etc/phantomjs/bin/phantomjs .

