#!/usr/bin/env bash
# Easy download/upload of files from Rapidshare and co

cd ~/local/src
git clone https://code.google.com/p/plowshare/

cd ./plowshare
mkdir ~/local/etc/plowshare
make install PREFIX=/usr/local/etc/plowshare

cd ~/local/bin
ln -s ../etc/plowshare/bin/plowdown 

