#!/usr/bin/env bash
# Easy download/upload of files from Rapidshare and co

cd /usr/local/src
git clone https://code.google.com/p/plowshare/

cd ./plowshare
mkdir /usr/local/etc/plowshare
make install PREFIX=/usr/local/etc/plowshare

cd /usr/local/bin
ln -s ../etc/plowshare/bin/plowdown 

