#!/usr/bin/env zsh
set -e

go get -u \
  github.com/open-pomodoro/openpomodoro-cli/cmd/pomodoro

# Making it globally available
ln \
  -s ~/.gvm/pkgsets/go1.16/global/bin/pomodoro \
  ~/local/bin/pomodoro
