#!/usr/bin/env bash
# Pyenv allow switching system-wide python versions.
#   Should be used to run external commands
set -e

# Dependencies for compiling python
sudo apt-get install \
  build-essential \
  curl \
  git \
  libbz2-dev \
  libffi-dev \
  liblzma-dev \
  libncurses5-dev \
  libncursesw5-dev \
  libreadline-dev \
  libsqlite3-dev \
  llvm \
  python-openssl \
  tk-dev \
  wget \
  xz-utils \
  zlib1g-dev

# Pyenv
cd ~/local/src
git clone git@github.com:pyenv/pyenv-installer.git
./pyenv-installer/bin/pyenv-installer

# Install both latest 3.x and latest 2.7.0
LATEST_PYTHON_3="3.9.5"
LATEST_PYTHON_2="2.7.18"
~/.pyenv/bin/pyenv install $LATEST_PYTHON_3

# Libssl needs to be installed for installing python 2
sudo apt install --reinstall libssl1.1
sudo apt-get install libssl-dev
~/.pyenv/bin/pyenv install $LATEST_PYTHON_2
# Make them both available, but looking for v3 first and v2 as fallback
~/.pyenv/bin/pyenv global $LATEST_PYTHON_3 $LATEST_PYTHON_2


# # Linter
# pip install flake8
# pip install flake8-bugbear
# pip install flake8-quotes
# pip install black
