#!/usr/bin/env bash

echo "Installing python dev"
sudo apt-get install python-dev
sudo apt-get install python-setuptools

echo "Installing pip"
sudo apt-get install python-pip
sudo pip install --upgrade pip

echo "Installing flake8 to check and lint code"
sudo pip install flake8

echo "Installing pygments"
sudo apt-get install python-pygments
