#!/usr/bin/env bash

echo "Installing Qmake compilers"

echo "Create directory"
cd ~/local/src
mkdir -p ./qmake
cd ./qmake

echo "Download installer"
wget http://download.qt-project.org/official_releases/online_installers/qt-opensource-linux-x64-online.run -O installer.run
chmod +x ./installer.run

echo "Please, install in ~/local/etc/qt"
./installer.run
