#!/usr/bin/env zsh

# FFcast to select a part of the screen
cd ~/local/src/
git clone git@github.com:lolilolicon/FFcast.git
cd ./FFcast
git submodule init
git submodule update
./bootstrap
./configure --prefix ~/local --enable-xrectsel
make
make install
