#!/usr/bin/env bash
set -ex

cd ~/local/tmp
wget \
  "https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb" \
  -O ripgrep.deb

sudo dpkg -i ripgrep.deb
sudo apt-get -f install
rm ~/local/tmp/ripgrep.deb
