#!/usr/bin/env bash

#Installing dependencies
sudo apt-get install build-essential
sudo apt-get install openssl
sudo apt-get install libreadline6
sudo apt-get install libreadline6-dev
sudo apt-get install curl
sudo apt-get install git-core
sudo apt-get install zlib1g
sudo apt-get install zlib1g-dev
sudo apt-get install libssl-dev
sudo apt-get install libyaml-dev
sudo apt-get install libsqlite3-dev
sudo apt-get install sqlite3
sudo apt-get install libxml2-dev
sudo apt-get install libxslt-dev
sudo apt-get install autoconf
sudo apt-get install libc6-dev
sudo apt-get install ncurses-dev
sudo apt-get install automake
sudo apt-get install libtool
sudo apt-get install bison
sudo apt-get install subversion

# Install rvm
curl -L https://get.rvm.io | bash -s stable --ruby
# Don't forget to add the following line in ~/.zshrc
# [[ -r $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm
source ~/.rvm/scripts/rvm
rvm get head
rvm reload

# Installing Ruby
rvm install 1.9.3
rvm install 1.9.3-dev

# Using Pry instead of irb
gem install pry
gem install awesome_print

# Installing mp3 tagging utility
gem install ruby-mp3info

# XML parsing made easy
gem install nokogiri







