#!/usr/bin/env zsh
# shellcheck disable=SC1091
set -ex

local RUBY_VERSION="3.1.2"

# Adding rbenv
cd ~/local/src
git clone git@github.com:rbenv/rbenv-installer.git
./rbenv-installer/bin/rbenv-installer

# Ruby needs a few dependencies to install correctly
sudo apt-get install \
  libssl-dev \
  zlib1g-dev

~/.rbenv/bin/rbenv install $RUBY_VERSION
~/.rbenv/bin/rbenv global $RUBY_VERSION

~/.rbenv/shims/gem install bundler
~/.rbenv/shims/gem install rubocop
~/.rbenv/shims/gem install awesome_print

# Auto-prefix commands with bundle exec
~/.rbenv/shims/gem install rubygems-bundler

# Installing rbenv-update plugin to update local ruby versions
mkdir -p ~/.rbenv/plugins
git clone git@github.com:rkh/rbenv-update.git ~/.rbenv/plugins/rbenv-update
