#!/usr/bin/env zsh

yarn global add live-server

# Weirdly enough, seems like v1.2.2 uses windows line ending on its executable,
# which breaks running it. It tries to use "node\r" instead of "node"
sudo apt-get install dos2unix
dos2unix --follow-symlink ~/.yarn/bin/live-server
