#!/usr/bin/env zsh

node-module-add live-server@1.2.1

# Weirdly enough, seems like v1.2.2 uses windows line ending on its executable,
# which breaks running it. It tries to use "node" instead of "node"
# sudo apt-get install dos2unix
# dos2unix --follow-symlink ~/.yarn/bin/live-server
