#!/usr/bin/env zsh
set -e

DOWNLOAD_URL="https://downloads.slack-edge.com/linux_releases/slack-desktop-4.15.0-amd64.deb"

cd ~/local/tmp
wget $DOWNLOAD_URL -O slack.deb
sudo dpkg -i ./slack.deb
sudo apt-get -f install
rm ./slack.deb
