#!/usr/bin/env zsh
# Installation from 
# https://linuxconfig.org/how-to-install-steam-on-ubuntu-18-04-bionic-beaver-linux
sudo dpkg --add-architecture i386
sudo apt update

sudo apt install wget gdebi-core libgl1-mesa-dri:i386 libgl1-mesa-glx:i386

cd /tmp
wget http://media.steampowered.com/client/installer/steam.deb
sudo gdebi ./steam.deb
