#!/usr/bin/env bash
# Subtitle-delay, to add or remove some delay to a srt file

echo "Downloading"
cd ~/local/etc
git clone git://github.com/kristijanbambir/subtitly.git

echo "Creating wrapper script"
cd ~/local/bin
echo "#!/usr/bin/env zsh" > subtitle-delay
echo "ruby ~/local/etc/subtitly/subtitly.rb \$@" >> subtitle-delay
