#!/usr/bin/env zsh

# Reading/Writing mails from cli
sudo apt-get install sup-mail

# Storing IMAP mails locally
sudo apt-get install offlineimap 
sudo apt-get install sqlite
# Sending emails
sudo apt-get install smsmtp
