#!/usr/bin/env bash

node-module-add \
	textlint \
	textlint-rule-alex \
	textlint-rule-common-misspellings \
	textlint-rule-editorconfig \
	textlint-rule-en-capitalization \
	textlint-rule-stop-words \
	textlint-rule-terminology \
	textlint-rule-write-good
