#!/usr/bin/env bash
set -ex

sudo apt-get install tmux

# xclip needed to copy to clipboard
sudo apt-get install xclip

# Tmux plugin manager
mkdir -p ~/.tmux/plugins
cd ~/.tmux/plugins
git clone git@github.com:tmux-plugins/tpm
echo "Now manually run ~/.tmux/plugins/tpm/tpm"
echo "And type [Alt-A] + I to install the tmux dependencies"
