#!/usr/bin/env bash

echo "Download source"
cd /usr/local/src/
wget -c http://downloads.sourceforge.net/project/tmux/tmux/tmux-1.7/tmux-1.7.tar.gz

echo "Extracting"
tar xvzf tmux-1.7.tar.gz
cd tmux-1.7

echo "Installing dependencies"
sudo apt-get install libevent-dev

echo "Configuring"
mkdir -p /usr/local/etc/tmux
./configure --prefix=/usr/local/etc/tmux

echo "Compiling"
make
make install

echo "Symlinking"
cd /usr/local/bin
ln -s ../etc/tmux/bin/tmux .
sudo ln -s /usr/local/etc/tmux/share/man/man1/tmux.1 /usr/local/share/man/man1/tmux.1


