#!/usr/bin/env bash
set -ex


RELEASE=`sed -n 's/VERSION_ID="\(.*\)"/\1/p' /etc/os-release`
wget "http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_$RELEASE/Release.key" -O /tmp/tomate-release-key
sudo apt-key add /tmp/tomate-release-key
sudo bash -c "echo 'deb http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_$RELEASE/ ./' > /etc/apt/sources.list.d/tomate.list"
sudo apt-get update && sudo apt-get install tomate-gtk

sudo apt-get install tomate-notify-plugin tomate-indicator-plugin
