#!/usr/bin/env bash
# For Ubuntu tweaks and config

# "Advanced" options
sudo apt-get install gnome-tweak-tools
# GUI to edit gconf options
sudo apt-get install gconf-editor
# Configuration editor for desktop related tweaks
sudo apt-get install dconf-editor
# Integrate LibreOffice with the top Unity menubar
sudo apt-get install lo-menubar
