#!/usr/bin/zsh
# Tools to encode and decode several video formats

# mencoder        : To encode/decode various movie files
sudo apt-get install mencoder
# handbrake       : To convert from and to several video formats
sudo add-apt-repository  ppa:stebbins/handbrake-releases
sudo apt-get update
sudo apt-get install handbrake-cli handbrake-gtk
# vcdimager       : To encode/decode vcd
sudo apt-get install vcdimager
# vlc             : For fun
sudo apt-get install vlc
# skype           : Video calls
sudo add-apt-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner"
sudo apt-get update && sudo apt-get install skype
# libdvdcss       : To read CSS encrypted DVDs
sudo apt-get install libdvdread4
sudo /usr/share/doc/libdvdread4/install-css.sh
