#!/usr/bin/env bash

echo "Clone git repo"
cd ~/local/etc
git clone git://github.com/bf4/vimeo_downloader.git

echo "Create wrapper script"
cd ~/local/bin

echo "#!/usr/bin/env bash" > ./vimeo-download
echo "/home/$USER/local/etc/vimeo_downloader/vimeo_downloader.rb video \$1" >> ./vimeo-download
echo "rm ./response.html" >> ./vimeo-download

