#!/usr/bin/env bash

echo "Downloading source from sourceforge"
cd ~/local/src
wget -c http://downloads.sourceforge.net/project/zsh/zsh/5.0.0/zsh-5.0.0.tar.gz 

echo "Extracting"
tar xvzf zsh-5.0.0.tar.gz
cd zsh-5.0.0

echo "Installing dependencies"
sudo apt-get install libncurses5-dev

echo "Configuring"
mkdir -p ~/local/etc/zsh
./configure --prefix=/home/$USER/local/etc/zsh

echo "Compiling"
make
# make check
make install

echo "Adding symlinks"
cd ~/local/bin/
ln -s ../etc/zsh/bin/zsh

echo "Changing current shell"
sudo chsh -s ~/local/bin/zsh $USER

echo "--------------"
echo "You should now reboot for the shell change to take effect correctly."
echo "--------------"


