# Global state for tabs
tabState = {
    # Manifest of tab data. Each key is a tabId, as generated by Kitty, and each
    # value is an object with the tab metadata (tabId, title, isFullscreen, etc.
    # Note: When a tab is closed, its metadata is not cleared but this shouldn't
    # be an issue.
    "manifest": {},
    # Array of all currently available tabIds, by order of appearance. This list
    # is automatically updated during the firstPass
    "allTabIds": [],
    # Subset of allTabIds that only contains the tabIds we actually want to
    # display. This is useful when we have a lot of tabs, and not enough real
    # estate to display them all. The pickTabsToDisplay function will fill that
    # array with the list of tabIds we want to keep, based on the available
    # space.
    "displayedTabIds": [],
}
