#!/usr/bin/env zsh
# Vale: prose linter
# https://github.com/vale-cli/vale
# Usage:
# $ tools/prose/vale/install
set -e

SCRIPT_DIR="${0:A:h}"
VALE_VERSION="3.16.0"
DOWNLOAD_URL="https://github.com/vale-cli/vale/releases/download/v${VALE_VERSION}/vale_${VALE_VERSION}_Linux_64-bit.tar.gz"

cd ~/local/bin
wget "$DOWNLOAD_URL" --output-document vale.tar.gz
tar --extract --gzip --file vale.tar.gz vale
rm vale.tar.gz
chmod +x vale

# Sync packages
vale sync --config "${SCRIPT_DIR}/vale.ini"
