#!/usr/bin/env zsh
# Generates a ~/.ssh/config file by concatenating :
# - files in ./private/config/ssh/local/{hostname}
# - default values

local CONFIG_DIR=~/.oroshi/config/basics/ssh
local LOCAL_FILES="~/.oroshi/private/config/basics/ssh/local/${HOSTNAME}/*"
local DEST_DIR=~/.ssh
local DEST_FILE=$DEST_DIR/config

mkdir -p $DEST_DIR
rm -f $DEST_FILE
touch $DEST_FILE

# Custom config
for localFile in ${~LOCAL_FILES}; do
	cat $localFile >> $DEST_FILE
done
# Default config
cat $CONFIG_DIR/default >> $DEST_FILE
