compressionLevel: 0

defaultSemverRangePrefix: ''

enableGlobalCache: true

# Keep old-school saving of dependencies in node_modules
# This makes debugging imported modules so much easier
nodeLinker: node-modules

# Use hardlinks to a global cache
nmMode: hardlinks-local

# Make sure each workspace has its own local node_modules
nmHoistingLimits: workspaces
