approvedGitRepositories:
  - "**"

compressionLevel: 0

defaultSemverRangePrefix: ""

enableGlobalCache: true

enableScripts: true

nmHoistingLimits: workspaces

nmMode: hardlinks-local

nodeLinker: node-modules

npmMinimalAgeGate: 0
