#!/usr/bin/zsh
# Deploy all config file on the current machine. This will look for a file
# names ~/.oroshi/scripts/deploy/local/{hostname} and execute it.
# Doing so, I can create custom deploy scripts for each of my machines, but
# still use the same command on all of them to update them.

local deployScript=~/.oroshi/scripts/deploy/local/$(hostname)

# No deploy script for current machine
if [[ ! -x $deployScript ]]; then
	echo "Unable to find deploy script for current hostname."
	echo "Please check that $deployScript exists and is executable."
	exit
fi

# Executing the deploy script
eval $deployScript
