#!/usr/bin/env bash
set -e

# Note: The .oroshi directory must obviously be cloned first, so I need to
# have git installed. Various submodules will also be required for some prompt
# method to work. The default .gitmodules reference them with a git endpoint,
# but will refuse the connection unless the propre private key is installed. If
# I don't have access to this private key (when I install on a computer that
# is not mine, for example), I can edit the ~/.oroshi/.config file to change all
# git@github.com:user/repo.git to https://github.com/user/repo and then install
# manually the following submodules:
# - git submodule update --init --remote -- config/zsh/plugins/zsh-syntax-highlighting
# - git submodule update --init --remote -- config/zsh/completion/docker-zsh-completion
# - git submodule update --init --remote -- scripts/bin/vit
# - git submodule update --init --remote -- scripts/bin/img
# - git submodule update --init --remote -- scripts/bin/pdf
# - git submodule update --init --remote -- scripts/bin/video

./scripts/install/cli/directories

# Configuring tools
./scripts/deploy/git
./scripts/deploy/apt-get
./scripts/deploy/dircolors
./scripts/deploy/wget
./scripts/deploy/watchers

# Compile stuff
./scripts/install/cli/make

# Editing and navigating
sudo apt-get install vim-gui-common
./scripts/deploy/vim

./scripts/install/cli/termite
./scripts/deploy/termite
./scripts/install/cli/tmux
./scripts/deploy/tmux
./scripts/install/cli/bat
./scripts/install/cli/curl
./scripts/install/cli/exa
./scripts/install/cli/rg
./scripts/install/cli/fzf
./scripts/install/cli/tree
./scripts/install/cli/trash
./scripts/install/cli/rename

# Zsh
./scripts/deploy/fonts
./scripts/deploy/zsh
./scripts/install/cli/zsh

# Shortcuts
./scripts/install/misc/xbindkeys
./scripts/install/misc/redshift

# Basic tools
./scripts/install/cli/archive
./scripts/install/cli/fonts
./scripts/install/cli/prettyping
./scripts/install/cli/direnv
./scripts/install/cli/fd
./scripts/install/cli/htop
./scripts/install/filesystem/ncdu

# Configuring tools
./scripts/deploy/apt-get
./scripts/deploy/dircolors
./scripts/deploy/wget
./scripts/deploy/watchers

# Getting Keepass, and thus the private key
./scripts/install/misc/dropbox
./scripts/install/misc/keepassx

echo "You need to get the private key into ~/.ssh/id_rsa"
echo "Press any key to continue when ready"
read -r

git submodule init
git submodule update
./scripts/deploy/hosts
./scripts/deploy/ssh

# Other tools requiring a working private key
./scripts/install/download/plowshare

# Languages


