#!/usr/bin/env bash
set -e

./scripts/install/cli/directories

# Basic editing and navigating
sudo apt-get install vim-gui-common
./scripts/install/cli/bat
./scripts/install/cli/exa
./scripts/install/cli/rg
./scripts/install/cli/fzf
./scripts/install/cli/archive

# Configuring tools
./scripts/deploy/apt-get
./scripts/deploy/dircolors
./scripts/deploy/git
./scripts/deploy/vim
./scripts/deploy/wget
./scripts/deploy/zsh

# Getting Keepass, and thus the private key
./scripts/install/misc/dropbox
./scripts/install/misc/keepassx

# Keyboard, need private


# Languages
./scripts/install/web/ruby
#





# Need private id_rsa key
git submodule init
git submodule update
./scripts/deploy/hosts
./scripts/deploy/ssh


