#!/usr/bin/env bash
# Link npm main config file to ~/.npmrc

# Paths
configFile=~/.oroshi/private/config/_languages/javascript/npmrc.conf
destFile=~/.npmrc

# Create link
ln -fs $configFile $destFile
