#!/usr/bin/env zsh
# Keybindings to interact with workspaces
set -e

# AATWS handles Alt-Tab, so disable the default switch-applications
gsettings set org.gnome.desktop.wm.keybindings switch-applications '@as []'

# Configure a 1x3 workspace matrix
dconf write /org/gnome/shell/extensions/wsmatrix/num-columns 1
dconf write /org/gnome/shell/extensions/wsmatrix/num-rows 3
dconf write /org/gnome/desktop/wm/preferences/num-workspaces 3

# [Super-Ctrl-Up/Down] Move across workspaces
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up    "['<Ctrl><Super>Up']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down  "['<Ctrl><Super>Down']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right '@as []'
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left  '@as []'

# [Super-Ctrl-Alt-Up/Down] Move windows across workspaces
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up    "['<Ctrl><Super><Alt>Up']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down  "['<Ctrl><Super><Alt>Down']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right '@as []'
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left  '@as []'
