#!/usr/bin/env zsh
# Keybindings to interact with workspaces

# Super-Tab {{{
# [Super-Tab] Shows a workspace overview
dconf write /org/gnome/shell/extensions/swmatrix/show-popup true
dconf write /org/gnome/shell/extensions/swmatrix/show-thumbnails true
dconf write /org/gnome/shell/extensions/swmatrix/show-workspace-names false
dconf write /org/gnome/shell/extensions/swmatrix/enable-popup-workspace-hover true

gsettings set org.gnome.desktop.wm.keybindings switch-applications '@as []'
gsettings --schemadir ~/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/schemas/ \
   set org.gnome.shell.extensions.wsmatrix-keybindings workspace-overview-toggle "['<Super>Tab']"
# }}}

# Configure a 3x3 workspace matrix
dconf write /org/gnome/shell/extensions/wsmatrix/num-columns 3
dconf write /org/gnome/shell/extensions/wsmatrix/num-rows 3
dconf write /org/gnome/desktop/wm/preferences/num-workspaces 9

# [Super-Ctrl-Arrows] Move across workspaces
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up    "['<Ctrl><Super>Up']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Ctrl><Super>Right']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down  "['<Ctrl><Super>Down']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left  "['<Ctrl><Super>Left']"

# [Super-Ctrl-Alt-Arrows] Move windows across workspace
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up      "['<Ctrl><Super><Alt>Up']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right   "['<Ctrl><Super><Alt>Right']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down    "['<Ctrl><Super><Alt>Down']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left    "['<Ctrl><Super><Alt>Left']"
# }}}
