#!/usr/bin/env bash
# Link zsh main config file to ~/.zshrc

CONFIG_DIR=~/.oroshi/config/term/zsh

# Create link
ln -fs \
	$CONFIG_DIR/zshrc.zsh \
	~/.zshrc
ln -fs \
	$CONFIG_DIR/zshenv.zsh \
	~/.zshenv

# Source file
echo "You should now reload ~/.zshrc"
