#!/usr/bin/env bash
# fstab config

# Paths
hostname=$(hostname)
destFile=/etc/fstab
configFile=~/.oroshi/private/config/fstab/$hostname.fstab

# Link the config file
if [[ -r $configFile ]]; then
	sudo cp "$configFile" "$destFile"
fi

# Copy cifs credentials files
mkdir -p ~/.cifs
for i in ~/.oroshi/private/config/cifs/*; do
	cp "$i" ~/.cifs;
done;

sudo mount -a
