#!/usr/bin/env bash
# Install python through pyenv which seems to be the less frustrating experience
# in 2023
set -e

# Pyenv will compile python locally on installation, so dependencies are
# required
sudo apt-get install \
	build-essential \
	curl \
	git \
	libbz2-dev \
	libffi-dev \
	liblzma-dev \
	libncurses5-dev \
	libncursesw5-dev \
	libreadline-dev \
	libsqlite3-dev \
	libssl-dev \
	llvm \
	tk-dev \
	wget \
	xz-utils \
	zlib3g-dev

# Cloning
git-directory-sync git@github.com:pyenv/pyenv.git ~/.pyenv

# Install latest 2 and 3 branches
LATEST_PYTHON_2="2.7.18"
LATEST_PYTHON_3="3.11.2"
~/.pyenv/bin/pyenv install --verbose $LATEST_PYTHON_2
~/.pyenv/bin/pyenv install --verbose $LATEST_PYTHON_3
# python will default to python 3, but python3 and python2 are also specifically
# available
~/.pyenv/bin/pyenv global $LATEST_PYTHON_3 $LATEST_PYTHON_2
