#!/usr/bin/env zsh
# Regenerate ./dist/oroshi.tmTheme from ./src/oroshi.xml

source ~/.oroshi/config/zsh/theming/env/colors.zsh

local currentDir=${0:a:h}

envsubst \
  < ${currentDir}/src/oroshi.xml \
  > ${currentDir}/dist/oroshi.tmTheme

bat cache --build
