#!/usr/bin/env zsh
# https://github.com/ReimuNotMoe/ydotool
# Command keyboard and mouse from a script.
# Wayland-compatible version of xdotool
set -e

local INSTALL_PATH=~/local/etc/ydotool

# Clone repo
cd ~/local/etc
git-directory-sync git@github.com:ReimuNotMoe/ydotool.git

# Build if not yet built
cd $INSTALL_PATH
if [[ ! -d ./build ]]; then
  mkdir build
  cd build
  cmake ..
  make -j "$(nproc)"
fi

# Put the binaries in /usr/local/bin/
sudo ln -fs $INSTALL_PATH/build/ydotool /usr/local/bin
sudo ln -fs $INSTALL_PATH/build/ydotoold /usr/local/bin

# Allow ydotool access to input events
sudo chmod +s /usr/local/bin/ydotool

${0:h}/deploy
