#!/usr/bin/env zsh
# Mute/Unmute microphone
kba "/org/gnome/settings-daemon/plugins/media-keys/mic-mute" "<Super>M"

# We disable them all, because the play/pause works on the last focused sound,
# so once one start playing a YouTube video, it's no longer possible to focus
# Spotify.
# Next song
kbz "/org/gnome/settings-daemon/plugins/media-keys/next"
# Previous song
kbz "/org/gnome/settings-daemon/plugins/media-keys/previous"
# Play/Pause
kbz "/org/gnome/settings-daemon/plugins/media-keys/play"
