#!/usr/bin/env bash
# App installer
# https://flatpak.org/
sudo apt-get install \
	flatpak \
	gnome-software-plugin-flatpak

flatpak remote-add \
	--if-not-exists flathub \
	https://flathub.org/repo/flathub.flatpakrepo
