#!/usr/bin/env zsh
set -e

DOWNLOAD_URL="https://github.com/kornelski/dssim/releases/download/3.2.3/dssim_3.2.3_amd64.deb"

cd ~/local/tmp
wget $DOWNLOAD_URL -O dssim.deb
sudo dpkg -i ./dssim.deb
sudo apt-get -f install
rm ./dssim.deb
