#!/usr/bin/env bash
# Image compression and conversion tools
set -e

# Basic image support
sudo apt-get install \
	libimage-exiftool-perl

# ImageMagick
~/.oroshi/scripts/install/image/imagemagick

# DSSIM
~/.oroshi/scripts/install/image/dssim

# WEBP
~/.oroshi/scripts/install/image/webp

# JPG
~/.oroshi/scripts/install/image/jpegoptim

# PNG
~/.oroshi/scripts/install/image/pngquant

# GIF
~/.oroshi/scripts/install/image/gifsicle
