#!/usr/bin/env bash
set -e

# Basic image support
sudo apt-get install \
	libimage-exiftool-perl

# DSSIM
~/.oroshi/scripts/install/image/imagemagick

# DSSIM
~/.oroshi/scripts/install/image/dssim

# WEBP
~/.oroshi/scripts/install/image/webp

# JPG
~/.oroshi/scripts/install/image/jpg
~/.oroshi/scripts/install/image/mozjpg

# PNG
~/.oroshi/scripts/install/image/png

# SVG
~/.oroshi/scripts/install/image/svg

# GIF
~/.oroshi/scripts/install/image/gifsicle
~/.oroshi/scripts/install/image/asciinema
