#!/usr/bin/env bash

sudo apt-get install \
  xpdf \
  pdftk \
  texlive-extra-utils
  xournal

## Note:
# If you're having an error similar to this one when attempting to convert
# a pdf:
# convert-im6.q16: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/421.
#
# Then, you need to edit the /etc/ImageMagick-6/policy.xml file
# You need to find a line similar to
# <policy domain="coder" rights="none" pattern="{PS,PS2,PS3,EPS,PDF,XPS}" />
# and comment it out.
# Sometimes, it's several lines instead of just one
#
## Note:
# If you're having an error similar to this one when merging images into a pdf:
# convert-im6.q16: cache resources exhausted `IMG_0007.jpg' @ error/cache.c/OpenPixelCache/4095.
#
# Then you need to edit the same file, and find the <policymap> section and
# comment out the following line:
# <policy domain="resource" name="disk" value="1GiB"/>
# This will remove limits and allow converting large files



