#!/usr/bin/env zsh
# Configure a custom keyboard layout with my own mappings
set -e

CONFIG_DIR="${0:h}/config"
DEST_DIR=~/.config/xkb

# Make symlinks to config files
mkdir -p $DEST_DIR

mkdir -p $DEST_DIR/rules
ln -fs $CONFIG_DIR/evdev.xml $DEST_DIR/rules/evdev.xml

mkdir -p $DEST_DIR/symbols
ln -fs $CONFIG_DIR/xkbmaprc.conf $DEST_DIR/symbols/oroshi

# Set both classic azerty and oroshi as enabled keyboard
gsettings reset org.gnome.desktop.input-sources sources
gsettings set   org.gnome.desktop.input-sources sources \
  "[('xkb', 'oroshi'), ('xkb', 'fr+azerty')]"
