# [c]ommit
alias vcRa='git-commit-remove-all'
alias vcR='git-commit-remove'
alias vcaf='git-commit-all -n'
alias vca='git-commit-all'
alias vcc='git-commit-staged'
alias vcd='vca -m "dev(deps): Update dependencies"'
alias vce='git-commit-edit'
alias vcef='git-commit-edit --no-verify'
alias vcla='git-commit-list --all'
alias vcl+='git-commit-list --more'
alias vcl='git-commit-list'
alias vcri='git rebase -i'
alias vcv='git show'
alias vcz='git-commit-cancel'
