# working [d]irectory
alias vdcl='git tabula-rasa'
alias vdc='git-directory-create'
alias vdca='git-directory-create-all'
alias vde='vim $(git-directory-root)/.git/config'
alias vdl='git status --short'
alias vdo='git-directory-open'
alias vdrd='vdr && cd ./docs'
alias vdrr='vd? && cd "$(git-directory-root -f)"'
alias vdr='vd? && cd "$(git-directory-root)"'
alias vd?='git-directory-is-repository'
