# [f]iles
alias vfR='git rm -r'
alias vfa='git-file-add'
alias vfd='git-file-diff'
alias vfds='git-file-diff --staged'
alias vffc='git-file-fix-conflicts'
alias vfforget='git rm --cached -r'
alias vfh='fzf-git-file-history'
alias vfl='git-file-list'
alias vfmv='git mv'
alias vfresurrect='git-file-resurrect'
alias vfrevert='git-file-revert'
alias vfua='git reset'
alias vfu='git-file-unstage'
