# [f]iles
alias vfR='git rm -r'
alias vfa='git-file-add'
alias vfdc='git diff -w --color-words --cached'
alias vfds='git diff -w --color-words --staged'
alias vfd='git diff -w --color-words'
alias vffc='git-file-fix-conflicts'
alias vfforget='git rm --cached -r'
alias vfh='fzf-git-file-history'
alias vfmv='git mv'
alias vfresurrect='git-file-resurrect'
alias vfrevert='git-file-revert'
alias vfua='git reset'
alias vfu='git-file-unstage'
