# [t]ags
alias vtRr='git-tag-remove-remote'
alias vtR='git-tag-remove'
alias vtc='git-tag-create'
alias vtlr='git-tag-list-remote'
alias vtl='git-tag-list'
alias vtpl='git fetch --tags'
alias vtps='git-tag-push'
alias vts='git-tag-switch'
alias vt.='git-tag-current'
