-- MUST HAVE
-- TODO: Folding that folds on expr and markers
-- TODO: Ensure I can complete filepaths
-- TODO: Add luacheck for linting lua
-- TODO: Find what works and what does not in a macro
-- TODO: Completion in commandline, to see fuzzy find of commands
-- TODO: Keybinding to rename the current file, in a popup
-- TODO: ChatGPT to explain code, quick chat, write tests, write documentation, etc
-- TODO: Ctrl-! to open the file system should open to where the current file is
-- TODO: Double check I can go to bottom of script and still have it centered

-- NICE TO HAVE
-- TODO: Display parent function name in statusbar
-- TODO: Git capabilities, like vfd in vim?
-- TODO: Might need to update nvim-treesitter to main branch, instead of master
-- TODO: Dim the lines when far from the cursor, to help focus? https://github.com/folke/twilight.nvim
-- TODO: Add a spinner when thinking in the statusline: https://github.com/folke/noice.nvim/issues/537
-- TODO: vim.cmd([[cab cc CodeCompanion]]) to remap cc to CodeCompanion in commandline
-- TODO: Check https://github.com/folke/tokyonight.nvim for methods to lighten/darken colors?
-- TODO: https://github.com/folke/trouble.nvim ? To see diagnostics
-- TODO: https://github.com/jpmens/jo create JSON from the CLI
