#!/usr/bin/env bash
set -ex

CONFIG_DIR="$(dirname "$0")/config"

# Generate the final config from a template
$CONFIG_DIR/generate-config

rm ~/.gitconfig
ln -s \
  $CONFIG_DIR/dist/gitconfig \
  ~/.gitconfig
