#!/usr/bin/env sh
gsettings set org.compiz.integrated command-1 "'terminator'"
gsettings set org.compiz.integrated command-2 "'chromium-browser --disable-gpu --profile-directory=\"Profile 2\"'"
gsettings set org.compiz.integrated command-3 "'chromium-browser --disable-gpu --profile-directory=\"Profile 1\"'"
gsettings set org.compiz.integrated command-4 "'keepassx ~/Dropbox/tim/config/keys.kdb'"
gsettings set org.compiz.integrated command-5 "''"
gsettings set org.compiz.integrated command-6 "''"
gsettings set org.compiz.integrated command-7 "'zeal'"
gsettings set org.compiz.integrated command-8 "'/home/tim/.oroshi/scripts/bin/record'"
gsettings set org.compiz.integrated command-9 "''"
gsettings set org.compiz.integrated command-10 "''"
gsettings set org.compiz.integrated command-11 "''"
gsettings set org.compiz.integrated command-12 "''"
gsettings set org.compiz.integrated command-21 "'/usr/bin/gnome-system-monitor -p'"
gsettings set org.compiz.integrated command-screenshot "'gnome-screenshot'"
gsettings set org.compiz.integrated command-window-screenshot "'gnome-screenshot --window'"
gsettings set org.compiz.integrated display-all-workspaces "true"
gsettings set org.compiz.integrated run-command-1 "['<Super>t']"
gsettings set org.compiz.integrated run-command-2 "['<Control><Super>C']"
gsettings set org.compiz.integrated run-command-3 "['<Control><Super><Alt>C']"
gsettings set org.compiz.integrated run-command-4 "['<Control><Super>K']"
gsettings set org.compiz.integrated run-command-5 "['disabled']"
gsettings set org.compiz.integrated run-command-6 "['disabled']"
gsettings set org.compiz.integrated run-command-7 "['<Super>z']"
gsettings set org.compiz.integrated run-command-8 "['<Super>q']"
gsettings set org.compiz.integrated run-command-9 "['disabled']"
gsettings set org.compiz.integrated run-command-10 "['disabled']"
gsettings set org.compiz.integrated run-command-11 "['disabled']"
gsettings set org.compiz.integrated run-command-12 "['disabled']"
gsettings set org.compiz.integrated run-command-21 "['<Control><Alt>Delete']"
gsettings set org.compiz.integrated show-hud "['disabled']"
