#!/usr/bin/env zsh
set -e

local CONFIG_DIR=~/.oroshi/config/misc/sgpt
local DEST_DIR=~/.config/shell_gpt

mkdir -p $DEST_DIR
mkdir -p $DEST_DIR/cache

ln -fs \
	$CONFIG_DIR/sgptrc.conf \
	$DEST_DIR/.sgptrc
