#!/usr/bin/env zsh
# Interact with Claude from the terminal
# https://www.anthropic.com/claude-code
set -e

# Context7 {{{
# Check up-to-date documentation
claude mcp add \
  --scope user \
  context7 \
  --transport http \
  https://mcp.context7.com/mcp
# }}}

# Make.com {{{
# Interact with make.com
claude mcp add \
  --scope user \
  make \
  --transport http \
  https://mcp.make.com/stream
# }}}

"${0:h}/deploy"
