# Global state for tabs
tabState = {
    # Manifest of tab data. Each key is a tabId, as generated by Kitty, and each
    # value is an object with the tab metadata (tabId, title, isFullscreen, etc.)
    # When a tab is closed, its manifest entry is pruned.
    "manifest": {},
    # Array of all currently available tabIds, by order of appearance. This list
    # is automatically updated during the first_pass
    "allTabIds": [],
    # Subset of allTabIds that only contains the tabIds we actually want to
    # display. This is useful when we have a lot of tabs, and not enough real
    # estate to display them all. The pick_tabs_to_display function will fill that
    # array with the list of tabIds we want to keep, based on the available
    # space.
    "displayedTabIds": [],
    # Dict of tab IDs that need user attention, mapping tabId → type
    # (populated once per render cycle from the attention file)
    "attentionIds": {},
    # ID of the currently active (focused) tab
    "activeTabId": None,
}
