#!/usr/bin/env zsh

CONFIG_DIR="${0:h}/config"
DEST_DIR=~/.config/gtk-3.0

# Note that we do HARD links, not SYM links
# File picker does not understand symlinks
rm -rf $DEST_DIR
mkdir -p $DEST_DIR
for configFile in $CONFIG_DIR/*; do
	ln \
		-fn $configFile \
		$DEST_DIR
done

# Disable "recent" startup mode in file chooser
gsettings set org.gtk.Settings.FileChooser startup-mode "/home/tim/Pictures"
