#!/usr/bin/env bash
set -e

# Enable 32bit architecture
sudo dpkg --add-architecture i386 

# Download and add key
wget -nc https://dl.winehq.org/wine-builds/winehq.key
sudo apt-key add winehq.key
rm winehq.key

# Add repo
sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main'
sudo apt-get update
sudo apt-get install --install-recommends winehq-stable
