#!/usr/bin/env zsh
# Regenerate ./dist/config.toml from ./src/config.toml
set -e

local currentDir=${0:a:h}

mkdir -p $currentDir/dist

colors-template-render \
  $currentDir/src/config.toml \
  >$currentDir/dist/config.toml
