#!/usr/bin/env zsh
# swhkb: Simple Wayland HotKey Daemon
# https://github.com/waycrate/swhkd/
set -e

cd ~/local/src
git-directory-sync git@github.com:waycrate/swhkd.git

# Install Rust first
if [[ ! -v commands[rustc] ]]; then
  echo "✘ Rust is not installed, you need to install rust first"
  exit 1
fi

# Dependecies needed
sudo apt-get install \
  libudev-dev

# Compilation
cd ./swhkd
make setup
make clean
make
sudo make install

# Making swhkd a setuid binary, so I don't need sudo to run it anymore
sudo chown root:root /usr/bin/swhkd
sudo chmod u+s swhkd

