#!/usr/bin/env zsh
# Configure custom global keybindings for Ubuntu 22.04
# Some keybindings can't be defined at the Ubuntu level, they seem to
# be intercepted before (for example <Super>I). For those, we use xbindkeys
# instead
set -e
local GSETTINGS_ROOT="org.gnome.settings-daemon.plugins.media-keys.custom-keybinding"
local GSETTINGS_DIRECTORY="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"

local                  shortcuts=(
  # Name                 Command                                               Binding
  "Calculator"           "gnome-calculator"                                    "Insert"
  "Chrome"               "google-chrome --profile-directory=\"Profile 5\""     "<Super>C"
  "Firefox"              "firefox"                                             "<Super>F"
  "Flameshot"            "/usr/bin/flameshot gui"                              "<Super>Print"
  "Keepass"              "keepassx ~/perso/Dropbox/tim/keys.kdbx"              "<Super>K"
  "Kitty"                "bin-zsh kitty-restore"                               "<Super>T"
  "Notion"               "google-chrome \'https://notion.so/\'"                "<Super>N"
  "Peek"                 "/home/tim/.oroshi/scripts/bin/peek"                  "<Super><Alt>Print"
  "Slack"                "/usr/bin/slack"                                      "<Super>S"
)



function gsettings_set() {
  local path=$1
  local key=$2
  local value=$3
  # echo "gsettings set $path $key $value"
  /usr/bin/gsettings set "$path" "$key" "$value"
}


# Iterating through all the bindings
local shortcut_count=$((${#shortcuts[@]} / 3))
local shortcut_inventory=()
for shortcut_index in {1..$shortcut_count}; do
  local custom_index=$((shortcut_index - 1))
  local array_index=$((1 + $custom_index * 3))

  local shortcut_name=$shortcuts[$array_index]
  local shortcut_command=$shortcuts[$array_index+1]
  local shortcut_binding=$shortcuts[$array_index+2]

  # Setting each shortcut individually
  local path="${GSETTINGS_ROOT}:${GSETTINGS_DIRECTORY}/custom${custom_index}/"
  gsettings_set "$path" "name" "'${shortcut_name}'"
  gsettings_set "$path" "command" "'${shortcut_command}'"
  gsettings_set "$path" "binding" "'${shortcut_binding}'"

  shortcut_inventory+=("'${GSETTINGS_DIRECTORY}/custom${custom_index}/'")
done

local mediaKeys="org.gnome.settings-daemon.plugins.media-keys"
gsettings_set "$mediaKeys" "custom-keybindings" "[${(j:,:)shortcut_inventory}]"


