#!/usr/bin/env zsh
# Keyboards and shortcuts > Screenshots
# We disable them all.
# We use flameshot and peek to do that, defined in custom keybindings

# Record a screencast interactively
kbz '/org/gnome/shell/keybindings/show-screen-recording-ui'

# Take a screenshot
kbz '/org/gnome/shell/keybindings/screenshot'

# Take a screenshot interactively
kbz '/org/gnome/shell/keybindings/show-screenshot-ui'

# Take a screenshot of a window
kbz '/org/gnome/shell/keybindings/screenshot-window'
