#!/usr/bin/env zsh
# Regenerate ./dist/oroshi.tmTheme from ./src/oroshi.xml

source $ZSH_CONFIG_PATH/theming/env/colors.zsh

local currentDir=${0:a:h}

envsubst \
	<${currentDir}/src/oroshi.xml \
	>${currentDir}/dist/oroshi.tmTheme

bat cache --build 1>/dev/null
