#!/usr/bin/env zsh
# Hostname: eddie
# Description: My tiny Samsung Netbook

cd ~/.oroshi/scripts/deploy/

# Config files
./ack
./fonts
./dircolors
./git
./hg
./hosts
./keybindings
./plowshare
./pry
./ssh
./sysctl
./terminator
./tidy
./vim
./wget
./xmodmap
./zsh
