#!/usr/bin/zsh
# Hostname: eddie
# Description: My tiny Samsung Netbook

cd ~/.oroshi/scripts/deploy/

# Config files
./ack
./fonts
./dircolors
./git
./hosts
./keybindings
./pry
./ssh
./terminator
./tidy
./xmodmap
./zsh
