#!/usr/bin/env bash
sudo apt-get install msttcorefonts

CONFIG_DIR=$(dirname "$0")/config

mkdir -p ~/.fonts
cp $CONFIG_DIR/DejaVuSansMono/*.ttf ~/.fonts
cp $CONFIG_DIR/Nerd.ttf ~/.fonts

fc-cache -f
