#!/usr/bin/zsh
# Link ack config to ~/.ackrc

# Paths
local configDir=~/.oroshi/config/ack
local configFile=${configDir}/ackrc
local destFile=~/.ackrc

# Link the config file
ln -fs $configFile $destFile
