#!/usr/bin/env bash
set -ex

# Deploy the theme
mkdir -p ~/.config/bat/themes/oroshi
ln -fs \
  ~/.oroshi/config/bat/dist/oroshi.tmTheme \
  ~/.config/bat/themes/oroshi/oroshi.tmTheme

bat cache --build &>/dev/null

