#!/usr/bin/env bash
set -ex

# Link the config file
mkdir -p ~/.config/bat
ln -fs \
	~/.oroshi/config/bat/batrc.conf \
	~/.config/bat/config

# Deploy the theme
mkdir -p ~/.config/bat/themes/oroshi
ln -fs \
	~/.oroshi/config/bat/dist/oroshi.tmTheme \
	~/.config/bat/themes/oroshi/oroshi.tmTheme

echo "Updating bat cache, to include the custom theme"
bat cache --build
