#!/usr/bin/env bash
# Cifs credentials

# Paths
destFile=/etc/cifs_serenity_tim
configFile=~/.oroshi/private/config/cifs/cifs_serenity_tim

# Link the config file
sudo ln -fs $configFile $destFile
sudo chmod 0600 $destFile
