#!/usr/bin/env ruby
require "json"

class DeployCssLint
  def initialize
    @config_dir = File.expand_path('~/.oroshi/config/csslint/')
    @csslintjson = File.join(@config_dir, "csslintrc.json")
    @csslintrc = File.expand_path("~/.csslintrc")
  end

  # Read a JSON file an return a ruby object
  def read_json(file)
    return JSON.parse(File.read(file))
  end

  # generate the final ~/.csslintrc file by concatenating the base with the
  # custom tags
  def generate
    base = []
    json = read_json(@csslintjson)
    json.each do |key, list|
      base << "--#{key}=#{list.join(',')}"
    end

    output = base.join(" ")
    File.write(@csslintrc, output);
  end

  def run
    generate
  end
end
DeployCssLint.new().run()
