#!/usr/bin/env zsh

mkdir -p ~/.davfs2/
# Link secrets files from private repo
chmod 0600 ~/.oroshi/private/config/davfs2/secrets
ln -fs ~/.oroshi/private/config/davfs2/secrets ~/.davfs2/secrets
# We also need to create an empty config file otherwise it will copoy the
# default one that does not work in user space
echo "" > ~/.davfs2/davfs2.conf

# echo "Remember that to access a davfs drive mounted in userspace you need to"
# echo "- be part of the davfs2 group (sudo adduser $USER davfs2)"
# echo "- reconfigure davfs2 to accept non-root to acces drive (sudo dpkg-reconfigure davfs2)"
