#!/usr/bin/env bash
# fstab config

# Paths
hostname=$(hostname)
destFile=/etc/fstab
configFile=~/.oroshi/private/config/fstab/$hostname.fstab

# Link the config file
if [[ -r $configFile ]]; then
	sudo cp $configFile $destFile
fi

# Copy cifs credentials files
mkdir -p ~/.cifs
for i in ~/.oroshi/private/config/cifs/*; do
	cp $i ~/.cifs;
done;

# Copy davfs secret file
mkdir -p ~/.davfs2/
# Link secrets files from private repo
chmod 0600 ~/.oroshi/private/config/davfs2/secrets
rm ~/.davfs2/secrets
ln -fs ~/.oroshi/private/config/davfs2/secrets ~/.davfs2/secrets
# We also need to create an empty config file otherwise it will copy the
# default one that does not work in userspace
echo "" > ~/.davfs2/davfs2.conf

sudo mount -a
