#!/usr/bin/env bash
# Link ~/.gitconfig and ~/.gitignore

# Paths
configDir=~/.oroshi/config/git

# Generic git config
ln -fs $configDir/gitconfig ~/.gitconfig
# Generic git ignore list
ln -fs $configDir/gitignore ~/.gitignore

