#!/usr/bin/env zsh

local SOURCE_PATH=~/.oroshi/config/jrnl/jrnl.yaml
local CONFIG_DIR=~/.config/jrnl/
local DESTINATION_PATH=${CONFIG_DIR}/jrnl.yaml

mkdir -p $CONFIG_DIR
ln -fs $SOURCE_PATH $DESTINATION_PATH
