#!/usr/bin/env zsh
set -e
# Each kitty conf is made of a main configuration file, and an host-specific
# override

mkdir -p ~/.config/kitty

local CONFIG_FILE=~/.config/kitty/kitty.conf
local CONFIG_OVERRIDE_FILE=~/.config/kitty/override.conf
local OROSHI_FILE=~/.oroshi/config/kitty/kitty.conf
local OROSHI_OVERRIDE_FILE=~/.oroshi/config/kitty/local/${HOST}.conf

# Base file
ln -fs $OROSHI_FILE $CONFIG_FILE
# Host specific file
ln -fs $OROSHI_OVERRIDE_FILE $CONFIG_OVERRIDE_FILE

