#!/usr/bin/env bash
# Default plowshare config

# Paths
destDir=~/.config/plowshare
destFile=$destDir/plowshare.conf
configFile=~/.oroshi/config/plowshare/plowshare.conf

# Link the config file
mkdir -p $destDir
ln -fs $configFile $destFile
