#!/usr/bin/env bash
# Default plowshare config

# Paths
local destDir=~/.config/plowshare
local destFile=$destDir/plowshare.conf
local configFile=~/.oroshi/config/plowshare/plowshare.conf

# Link the config file
mkdir -p $destDir
ln -fs $configFile $destFile
