#!/usr/bin/env bash
# Default plowshare config

src=~/.oroshi/private/config/plowshare/plowshare.conf
dest=~/.config/plowshare/plowshare.conf

mkdir -p "$(dirname $dest)"
cp -f $src $dest
chmod 600 $dest
