#!/usr/bin/env bash
# Copy redshift config to ~/.config/redshift.conf

# Paths
configDir=~/.oroshi/config/redshift
configFile=${configDir}/redshift.conf
destFile=~/.config/redshift.conf

# Link the config file
ln -fs $configFile $destFile

# Use a custom icon
~/.oroshi/config/ubuntu/20.04/redshift
