#!/usr/bin/env bash
# Copy redshift config to ~/.config/redshift.conf

# Paths
configDir=~/.oroshi/config/redshift
configFile=${configDir}/redshift.conf
destFile=~/.config/redshift.conf

# Link the config file
ln -fs $configFile $destFile

# Add a script to resume redshift after waking up from suspend
sudo cp \
  ~/.oroshi/config/redshift/wakeup \
  /usr/lib/pm-utils/sleep.d/z_redshift
