#!/usr/bin/zsh
# Copy Terminator config to ~/.config/terminator/config

# Paths
local configDir=~/.oroshi/config/terminator
local configFile=${configDir}/default.terminator
local destDir=~/.config/terminator
local destFile=${destDir}/config

# Copy config file
mkdir -p $destDir
ln -fs $configFile $destFile
