#!/usr/bin/env bash
# Link Terminator config to ~/.config/terminator/config

# Paths
configDir=~/.oroshi/config/terminator
configFile=${configDir}/default.terminator
destDir=~/.config/terminator
destFile=${destDir}/config

# Link the config file
mkdir -p $destDir
ln -fs $configFile $destFile
