#!/usr/bin/env bash
# Copy html5-tidy config to ~/.tidyrc

# Paths
configDir=~/.oroshi/config/tidy
configFile=${configDir}/tidyrc
destFile=~/.tidyrc

# Link the config file
ln -fs $configFile $destFile
