#!/usr/bin/env zsh
# Creates directories needed by vim and link vim config to ~/.vim and ~/.vimrc.

# Paths
local configDir=~/.oroshi/config/vim
local configFile=${configDir}/vimrc
local destDir=~/.vim
local destFile=~/.vimrc

# Create directories needed by vim
mkdir -p $destDir/swap
mkdir -p $destDir/backup
mkdir -p $destDir/undo
mkdir -p $destDir/view
mkdir -p $destDir/cache/ctrlp

# Link other config directories
ln -fns $configDir/autoload $destDir/autoload
ln -fns $configDir/bundle/enabled $destDir/bundle
ln -fns $configDir/colors $destDir/colors
ln -fns $configDir/after $destDir/after
ln -fns $configDir/includes $destDir/includes

# Vimrc
ln -fs $configFile $destFile
