#!/usr/bin/env bash
# Creates directories needed by vim and link vim config to ~/.vim and ~/.vimrc.

# Paths
configDir=~/.oroshi/config/vim
configFile=${configDir}/vimrc
destDir=~/.vim
destFile=~/.vimrc

# Create directories needed by vim
mkdir -p $destDir/swap
mkdir -p $destDir/backup
mkdir -p $destDir/undo
mkdir -p $destDir/view
mkdir -p $destDir/plugins

# Link other config directories
ln -fns $configDir/after $destDir/after
ln -fns $configDir/autoload $destDir/autoload
ln -fns $configDir/bundle/enabled $destDir/bundle
ln -fns $configDir/colors $destDir/colors
ln -fns $configDir/includes $destDir/includes
ln -fns $configDir/snippets $destDir/UltiSnips
ln -fns $configDir/spell $destDir/spell
ln -fns $configDir/syntax $destDir/syntax

# Vimrc
ln -fs $configFile $destFile
