#!/usr/bin/env zsh
# Clear the current ~/.Xmodmap file, and create a new one by concatenating
# (optional) local file and default xmodmap config.

# Paths
local destFile=~/.Xmodmap
local configDir=~/.oroshi/config/xmodmap
local defaultFile=${configDir}/xmodmaprc
local localFile=${configDir}/local/${HOST}.xmodmap


# Starting with an empty file
rm -f $destFile

# Adding the default configuration last
cp $defaultFile $destFile

# Adding the local config
if [[ -r $localFile ]]; then
	cat $localFile >> $destFile
fi

# Reload xmodmap
setxkbmap fr
xmodmap $destFile

