#!/usr/bin/env bash

# Force pinning version numbers (no ^ nor ~)
yarn config set save-prefix ""

# Following line might not work and require to manually edit .yarnrc
# yarn config set "--run-silent" true

