#!/usr/bin/env zsh
# Link zsh main config file to ~/.zshrc

# Paths
local configFile=~/.oroshi/config/zsh/main.zsh
local destFile=~/.zshrc

# Create link
ln -fs $configFile $destFile

# Source file
source $destFile
