#!/usr/bin/env bash
# Link zsh main config file to ~/.zshrc

# Create link
ln -fs \
	~/.oroshi/config/zsh/zshrc.zsh \
	~/.zshrc
ln -fs \
	~/.oroshi/config/zsh/zshenv.zsh \
	~/.zshenv

# Source file
echo "You should now reload ~/.zshrc"
