#!/usr/bin/env bash
# Link zsh main config file to ~/.zshrc

# Paths
configFile=~/.oroshi/config/zsh/main.zsh
destFile=~/.zshrc

# Create link
ln -fs $configFile $destFile

# Source file
echo "You should now reload ~/.zshrc"
