# [w]orktree
alias vwc='git-worktree-create'
alias vwl='git-worktree-list'
alias vwpl='git-worktree-pull'
alias vwps='git-worktree-push'
alias vws='git-worktree-switch'
alias vwR='git-worktree-delete'
alias vwmv='git-worktree-rename'
alias vwsm='vws main'
alias vwrv='review worktree'
