#!/usr/bin/env bash
set -ex

CONFIG_DIR=~/.oroshi/config/cli/bat
DEST_DIR=~/.config/bat

# Link the config file
mkdir -p $CONFIG_DIR
ln -fs \
	$CONFIG_DIR/batrc.conf \
	$DEST_DIR/config

# Deploy the theme
mkdir -p $DEST_DIR/themes/oroshi
ln -fs \
	$CONFIG_DIR/dist/oroshi.tmTheme \
	$DEST_DIR/themes/oroshi/oroshi.tmTheme

echo "Updating bat cache, to include the custom theme"
bat cache --build
