#!/usr/bin/env zsh
# Clear the current ~/.Xmodmap file, and create a new one by concatenating
# (optional) local file and default xmodmap config.
CONFIG_DIR="${0:h}/config"
LOCAL_FILE=$CONFIG_DIR/local/${HOSTNAME}.xmodmap
DEST_FILE=~/.Xmodmap

# Starting with an empty file
rm -f $DEST_FILE

# Adding the default configuration first
cp $CONFIG_DIR/xmodmaprc $DEST_FILE

# Adding the local config
if [[ -r $LOCAL_FILE ]]; then
	cat $LOCAL_FILE >>$DEST_FILE
fi

# Reload xmodmap
setxkbmap fr
xmodmap $DEST_FILE
