#!/usr/bin/env zsh
# Zoom: Online video calls
# Note: Zoom UI and controls never really feel native on Ubuntu.
# The best I found, was the version from snap (rather than the .deb from the
# website or the one from flatpak) was the most readable and responsive.
set -e

sudo snap install zoom-client
