# Defaults : https://github.com/brigade/scss-lint/blob/master/config/default.yml
linters:

  EmptyLineBetweenBlocks:
    enabled: false

  # Hexadecimal in colors should be uppercase
  HexNotation:
    enabled: true
    style: uppercase

  # Do not allow #selector in CSS
  IdSelector:
    enabled: false

  # Remove leading zero in units
  LeadingZero:
    enabled: true

  # Allow $my-variable as well as $MY_CONSTANT
  NameFormat:
    enabled: rue
    allow_leading_underscore: true
    style: exclude_zero
    convention: '(^[A-Z0-9_]+$)|(^[a-z0-9-]+$)'

  # Do not allow overqualifying an element
  QualifyingElement:
    enabled: true
    severity: error
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false

  # Prefer block__element--modifier syntax
  SelectorFormat:
    enabled: true
    convention: 'hyphenated_BEM'

  # Using double-quotes
  StringQuotes:
    enabled: true
    style: double_quotes
 

