#!/usr/bin/env sh

echo "Global commit"
exit 0

# # Redirect output to stderr.
# exec 1>&2
#
# # Check if lines tagged as "DO NOT COMMIT" or "NO COMMIT" (case insensitive) are included.
# do_not_commits=$(git diff --cached -z HEAD -S "(DO\\s*)?NO(T)?\\s*COMMIT" --pickaxe-regex --regexp-ignore-case --name-only)
# if [[ ! -z "$do_not_commits" ]]; then
# 	echo "ERROR: The following files contain not-to-be-committed lines:"
# 	echo $do_not_commits
# 	exit 1
# fi
