#!/usr/bin/env zsh
# Default plowshare config

local CONFIG_DIR=~/.oroshi/private/config/download/plowshare
local DEST_DIR=~/.config/plowshare

mkdir -p $DEST_DIR
cp \
	-f \
	$CONFIG_DIR/plowshare.conf \
	$DEST_DIR/plowshare.conf

chmod 600 $DEST_DIR/plowshare.conf
