#!/usr/bin/env zsh
# Hyperfine is a commandline benchmarking tool
# https://github.com/sharkdp/hyperfine
set -ex

DOWNLOAD_URL="https://github.com/sharkdp/hyperfine/releases/download/v1.20.0/hyperfine-musl_1.20.0_amd64.deb"

cd ~/local/tmp
wget "$DOWNLOAD_URL" -O hyperfine.deb

sudo dpkg -i ./hyperfine.deb
sudo apt-get -f install

rm ./hyperfine.deb
