#!/usr/bin/env zsh
# Add Autokey config
set -e

local CONFIG_DIR=~/.oroshi/private/config/worktools/autokey
local DEST_DIR=~/.config/autokey

mkdir -p $DEST_DIR

# Generic configuration
rm -rf $DEST_DIR/autokey.json
ln -s $CONFIG_DIR/autokey.json $DEST_DIR/autokey.json

# Custom scripts and phrases
rm -rf ~/.config/autokey/data
ln -s $CONFIG_DIR/data $DEST_DIR/data
