#!/usr/bin/env zsh
# Switch to a specific workspace
# Usage:
# $ workspace-switch 1   # Switch to first workspace
# $ workspace-switch 5   # Switch to center workspace

# workspaces ar 0-indexed
local workspaceIndex=$(echo "$1 - 1" | bc)

wmctrl -s $workspaceIndex
