#!/usr/bin/env bash
set -e

# Instructions as per
# https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository

# Remove old installs
sudo apt-get remove docker docker-engine docker.io

# Setting system up to date
sudo apt-get update

# Allow using repo over HTTPS
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

# Use Docker key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

# Add official repo
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

# Setting system up to date again
sudo apt-get update

# Actually installing docker
sudo apt-get install docker-ce docker-ce-cli containerd.io

# Add current user to the docker group
sudo usermod -aG docker "$USER"

# Start docker on bood
sudo systemctl enable docker

echo "You should log out and back in for this to work"

