#!/usr/bin/env bash

# Download and install docker
wget -qO- https://get.docker.com/ | sh

# Add current user to the docker group
sudo usermod -aG docker "$USER"

# Install docker compose
curl -L "https://github.com/docker/compose/releases/download/1.3.3/docker-compose-$(uname -s)-$(uname -m)" > ~/local/bin/docker-compose
chmod +x ~/local/bin/docker-compose

# Init the docker daemon
sudo systemctl enable docker

