#!/usr/bin/env sh
# A better and faster find
# https://github.com/sharkdp/fd
set -e

cd ~/local/tmp
wget \
	"https://github.com/sharkdp/fd/releases/download/v8.5.2/fd_8.5.2_amd64.deb" \
	-O fd.deb

sudo dpkg -i fd.deb
sudo apt-get -f install
rm ~/local/tmp/fd.deb
