#!/usr/bin/env bash
sudo apt-get install msttcorefonts

mkdir -p ~/.fonts
cp ~/.oroshi/config/fonts/DejaVuSansMonoWithOcticons.ttf ~/.fonts
cp ~/.oroshi/config/fonts/PowerlineSymbols.ttf ~/.fonts

cp ~/.oroshi/config/fonts/*.ttf ~/.fonts/
