#!/usr/bin/env bash

echo "Installing compilers"

sudo apt-get install build-essential \
                     xsltproc \
                     g++ \
                     libxml2-dev \
                     llibxslt1-dev
