#!/usr/bin/env bash

echo "Installing compilers"

sudo apt-get install build-essential
sudo apt-get install xsltproc
sudo apt-get install g++

echo "xml libraries"
sudo apt-get install libxml2-dev
sudo apt-get install llibxslt1-dev
