#!/usr/bin/env bash

# Try on apt first
sudo apt-get install prettyping && exit 0

cd ~/local/bin
curl -O https://raw.githubusercontent.com/denilsonsa/prettyping/master/prettyping
chmod +x prettyping

