#!/usr/bin/env bash
set -ex

cd ~/local/tmp
wget \
  "https://github.com/BurntSushi/ripgrep/releases/download/0.10.0/ripgrep_0.10.0_amd64.deb" \
  -O ripgrep.deb

sudo dpkg -i ripgrep.deb
sudo apt-get -f install
