#!/usr/bin/env bash
set -ex

cd ~/local/tmp
wget \
  "https://github.com/BurntSushi/ripgrep/releases/download/0.3.2/ripgrep-0.3.2-x86_64-unknown-linux-musl.tar.gz" \
  -O ripgrep.tar.gz
tar xvzf ripgrep.tar.gz
mv ./ripgrep-0.3.2-x86_64-unknown-linux-musl/rg ~/local/bin



