#!/usr/bin/env bash
set -ex

cd ~/local/tmp
wget \
  "https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep_12.1.1_amd64.deb" \
  -O ripgrep.deb

sudo dpkg -i ripgrep.deb
sudo apt-get -f install
rm ~/local/tmp/ripgrep.deb
