#!/usr/bin/env bash
set -ex

# Termite needs a custom version of vte available, that exposes some of the
# internals
echo "Install compilation dependencies"
sudo apt-get install \
  gnutls-bin \
  gperf \
  gtk-doc-tools \
  g++ \
  libgirepository1.0-dev \
  libglib3.0-cil-dev \
  libgnutls28-dev \
  libgtk-3-dev \
  libpcre2-dev \
  libxml2-utils \
  valac

echo "Clone patched vte version"
cd ~/local/src/
git clone https://github.com/thestinger/vte-ng.git
cd ./vte-ng
./autogen.sh && make && sudo make install

echo "Copy libs"
sudo cp /usr/local/lib/libvte-2.91.* /usr/lib
sudo ldconfig

echo "Clone termite"
cd ~/local/src/
git clone --recursive https://github.com/thestinger/termite.git
cd ./termite
make && sudo make install






