#!/usr/bin/env zsh
# Termite needs a custom version of vte available, that exposes some of the
# internals


echo "Install compilation dependencies"
sudo apt-get install g++ libgtk-3-dev gtk-doc-tools gnutls-bin valac
sudo apt-get install libglib3.0-cil-dev libgnutls28-dev libgirepository1.0-dev
sudo apt-get install libxml2-utils gperf

echo "Clone patched vte version"
cd ~/local/src/
git clone https://github.com/thestinger/vte-ng.git
cd ./vte-ng
./autogen.sh && make && sudo make install

echo "Clone termite"
cd ~/local/src/
git clone --recursive https://github.com/thestinger/termite.git
cd ./termite
make && sudo make install

echo "Copy libs"
sudo cp /usr/local/lib/libvte-2.91.a /usr/local/lib/libvte-2.91.la \
/usr/local/lib/libvte-2.91.so /usr/local/lib/libvte-2.91.so.0 \
/usr/local/lib/libvte-2.91.so.0.4000.2 /usr/lib





