#!/usr/bin/env bash


echo "Download source"
cd ~/local/src/
git clone git@github.com:tmux/tmux.git
cd ./tmux

echo "Install dependencies"
sudo apt-get install libevent-dev

echo "Configure"
sh autogen.sh
./configure --prefix="/home/$USER/local/"
make

echo "Symlink"
cd ~/local/bin
ln -s ../src/tmux/tmux .
exit 1
