#!/usr/bin/env bash
set -ex

echo "Download source"
cd ~/local/src/
git clone git@github.com:tmux/tmux.git
cd ./tmux

echo "Install dependencies"
sudo apt-get install libevent-dev
# For copy/paste
sudo apt-get install xclip

echo "Configure"
sudo apt-get install \
  automake \
  libncurses5-dev

sh autogen.sh
./configure --prefix="/home/$USER/local/"
make

echo "Symlink"
cd ~/local/bin
ln -s ../src/tmux/tmux .

# Tmux plugin manager
cd ~/local/src
git clone https://github.com/tmux-plugins/tpm ./tpm
echo "Now run [Prefix] + I to install the tmux dependencies"

exit 1
