#!/usr/bin/env zsh
# Install drivers for the Brother HL-L2375DW

DRIVER_PATH="${0:h}/driver-Brother-HL-L2375DW.deb"

# Allow installing i386 packages (that should be compatible with amd64 anyway)
sudo dpkg --add-architecture i386

install-deb $DRIVER_PATH
