#!/usr/bin/env zsh
# Called whenever the PC boots
# Function to reload the Gnome topbar config, as Gnome extensions tend to lose
# their settings when coming from sleep.

# Setup debug log
DEBUG_LOG=/home/tim/local/tmp/autostart.log
rm -rf $DEBUG_LOG
function debug() {
  echo "[$(date)] $1" >>$DEBUG_LOG
}
debug "==== <onstartup> ===="

# Actually reload the topbar
function reloadTopBar() {
  debug "reloadTopBar"
  ~/.oroshi/scripts/deploy/ubuntu/24.04/topbar
}
reloadTopBar

# Move to workspace 5 (main)
wmctrl -s 4

# We also listens to DBus events, and calls it again when we get back from sleep
lastEventTime=0
timeBetweenEvents=5
function processLogLine() {
  local input="$1"
  local currentTime=$(date +%s)

  # Skip if not a matching line
  if [[ $input != *"member=WakeUpScreen"* ]]; then return; fi

  # Skip if too short a time since last event
  debug "Found line:"
  debug $input
  if ((currentTime - lastEventTime < timeBetweenEvents)); then return; fi

  # Found, reload the bar
  reloadTopBar
  lastEventTime=$currentTime
}
#
dbus-monitor \
  --session "type='signal',interface=org.gnome.ScreenSaver,member=WakeUpScreen" |
  (while true; do
    read logLine
    processLogLine "$logLine"
  done)

debug "==== </onstartup> ===="
