#!/usr/bin/env zsh
# Called whenever the PC boots

local LOG_FILE=/home/tim/local/tmp/autostart

rm -rf $LOG_FILE

# Function to reload the Gnome topbar config, as Gnome extensions tend to lose
# their settings when coming from sleep.
function reloadTopbar() {
  ~/.oroshi/scripts/deploy/ubuntu/24.04/topbar
}
reloadTopbar


# We also listens to DBus events, and calls it again when we get back from sleep
dbus-monitor \
  --session "type='signal',interface=org.gnome.ScreenSaver,member=WakeUpScreen" | 
  (while true; do
      read logLine;

      # We still need to grep on the actual string because the script display
      # some generic string at the beginning
      if [[ $logLine = *"member=WakeUpScreen"* ]]; then
        reloadTopbar
      fi

    done)
