#!/usr/bin/env zsh
# selene: Lua linter
# https://github.com/Kampfkarren/selene
set -e

local DOWNLOAD_URL="https://github.com/Kampfkarren/selene/releases/download/0.31.0/selene-light-0.31.0-linux.zip"
local BINARY_NAME="selene"

cd ~/local/tmp

# Download
rm -f "${BINARY_NAME}.zip"
wget "$DOWNLOAD_URL" -O "${BINARY_NAME}.zip"

# Extract
extract "${BINARY_NAME}.zip"
rm "${BINARY_NAME}.zip"

# Move binary
chmod +x "$BINARY_NAME"
mv -f "$BINARY_NAME" ~/local/bin/$BINARY_NAME
