#!/usr/bin/env zsh
# Regenerate ./dist/gitconfig from ./src/gitconfig
set -e

local currentDir=${0:a:h}

mkdir -p $currentDir/dist

colors-template-render \
  $currentDir/src/gitconfig \
  >$currentDir/dist/gitconfig
