#!/usr/bin/env zsh
# Regenerate ./dist/rgrc.conf from ./src/rgrc.conf
set -e

local currentDir=${0:a:h}

mkdir -p $currentDir/dist

colors-template-render \
  $currentDir/src/rgrc.conf \
  >$currentDir/dist/rgrc.conf
