#!/usr/bin/env zsh
echo "Note that cmus will ask for configuring a DECNet node. Choose configure later"

echo "Downloading and installing"
sudo apt-get install cmus

echo "You might need to restart your computer for the installation to work."
