#!/usr/bin/env bash
set -e

# Utilities
~/.oroshi/scripts/install/music/sox

# Formats
~/.oroshi/scripts/install/music/mp3
~/.oroshi/scripts/install/music/ogg
~/.oroshi/scripts/install/music/flac

# Players
~/.oroshi/scripts/install/music/cmus
~/.oroshi/scripts/install/music/mplayer
