#!/usr/bin/env zsh
# Zoom: Online video calls
# There are various ways to install Zoom (official .deb on their website, snap
# or flatpak). I found that the official .deb was the best as it allow for
# screensharing, which the other seem to have trouble with.
set -e

local DOWNLOAD_URL="https://zoom.us/client/7.2.1.5760/zoom_amd64.deb"

# Download .deb
cd ~/local/tmp
wget $DOWNLOAD_URL -O zoom.deb

# Install .deb; apt resolves the dependencies the package declares
sudo apt update
sudo apt install ./zoom.deb
