#!/usr/bin/env zsh
# Top bar (aka. System Tray) config

# Note that we need to use dconf rather than gsettings here as extensions
# might not have a schema registered, so using gsettings will do nothing
#
# Options are grouped by icon as they are displayed in the top bar, even if the
# config spans several extensions. They are ordered from left to right

dconf write /org/gnome/shell/extensions/unite/reduce-panel-spacing true

# "Activities" button (zoom out of everything)
dconf write /org/gnome/shell/extensions/just-perfection/activities-button false

# Window buttons (down, window, maximize)
dconf write /org/gnome/shell/extensions/unite/show-window-buttons "'always'"
dconf write /org/gnome/shell/extensions/unite/window-buttons-placement "'first'"
dconf write /org/gnome/shell/extensions/unite/window-buttons-theme "'adwaita'"

# Spotify
dconf write /org/gnome/shell/extensions/sp-tray/display-mode 0
dconf write /org/gnome/shell/extensions/sp-tray/logo-position 0
dconf write /org/gnome/shell/extensions/sp-tray/title-max-length 50
dconf write /org/gnome/shell/extensions/sp-tray/metadata-when-pause false
dconf write /org/gnome/shell/extensions/sp-tray/paused "''"

# Clock
dconf write /org/gnome/shell/extensions/just-perfection/clock-menu-position 1
dconf write /org/gnome/shell/extensions/just-perfection/clock-menu-position-offset 1
dconf write /org/gnome/shell/extensions/just-perfection/world-clock false
dconf write /org/gnome/shell/extensions/just-perfection/weather false
dconf write /org/gnome/shell/extensions/just-perfection/events-button false

# Hide keyboard indicator
dconf write /org/gnome/shell/extensions/just-perfection/keyboard-layout false
# Hide accessibility icon
dconf write /org/gnome/shell/extensions/just-perfection/accessibility-menu false

# Quick settings
gsettings set org.gnome.desktop.interface show-battery-percentage true
dconf write /org/gnome/shell/extensions/just-perfection/quick-settings-dark-mode false
dconf write /org/gnome/shell/extensions/just-perfection/quick-settings-night-light false
dconf write /org/gnome/shell/extensions/just-perfection/quick-settings-airplane-mode false


# }}}

