#!/usr/bin/env zsh
# Update generic Ubuntu config, for a better usage suited to my preference.
# This will do small things like remove the key repeat delay, enable dark mode,
# or the orange color filter, etc.
#
# The best way to know which values to update is to run dconf-watch, then to
# change values in the Settings UI, then save it here, so I only have to run
# this script later to find my config back.

# Disable Dock on the left side
gnome-extensions disable ubuntu-dock@ubuntu.com

# Mouse {{{
gsettings set org.gnome.desktop.peripherals.mouse speed -0.19000
# }}}

# Touchpad {{{
# Speed
gsettings set org.gnome.desktop.peripherals.touchpad speed 0.65000
# Scroll direction
gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll false
# }}}

# Appearance {{{
# When laptop starts, display Desktop
dconf write /org/gnome/shell/extensions/just-perfection/startup-status 0
# Dark mode
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface gtk-theme 'Yaru-dark'
# Night light
gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-automatic false
gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-from 4.0
gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-to 3.5
gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature 4200
# Accessibility
gsettings set org.gnome.desktop.interface enable-animations false
dconf   write /org/gnome/shell/extensions/just-perfection/animation 0
gsettings set org.gnome.desktop.interface text-scaling-factor 1.25
# }}}

# Top bar (aka. Tray) {{{

# Requires the following gnome extensions:
# - Just Perfection
# - Unite
# Note that we need to use dconf rather than gsettings here as extensions
# might not have a schema registered, so using gsettings will do nothing
#
# Options are grouped by icon as they are displayed in the top bar, even if the
# config spans several extensions. They are ordered from left to right

dconf write /org/gnome/shell/extensions/unite/reduce-panel-spacing true

# "Activities" button (zoom out of everything)
dconf write /org/gnome/shell/extensions/just-perfection/activities-button false

# Window buttons (down, window, maximize)
dconf write /org/gnome/shell/extensions/unite/show-window-buttons "'always'"
dconf write /org/gnome/shell/extensions/unite/window-buttons-placement "'first'"
dconf write /org/gnome/shell/extensions/unite/window-buttons-theme "'adwaita'"

# Spotify
dconf write /org/gnome/shell/extensions/sp-tray/display-mode 0
dconf write /org/gnome/shell/extensions/sp-tray/logo-position 0
dconf write /org/gnome/shell/extensions/sp-tray/title-max-length 50
dconf write /org/gnome/shell/extensions/sp-tray/metadata-when-pause false
dconf write /org/gnome/shell/extensions/sp-tray/paused "''"

# Clock
dconf write /org/gnome/shell/extensions/just-perfection/clock-menu-position 1
dconf write /org/gnome/shell/extensions/just-perfection/clock-menu-position-offset 1
dconf write /org/gnome/shell/extensions/just-perfection/world-clock false
dconf write /org/gnome/shell/extensions/just-perfection/weather false
dconf write /org/gnome/shell/extensions/just-perfection/events-button false

# Hide keyboard indicator
dconf write /org/gnome/shell/extensions/just-perfection/keyboard-layout false
# Hide accessibility icon
dconf write /org/gnome/shell/extensions/just-perfection/accessibility-menu false

# Quick settings
gsettings set org.gnome.desktop.interface show-battery-percentage true
dconf write /org/gnome/shell/extensions/just-perfection/quick-settings-dark-mode false
dconf write /org/gnome/shell/extensions/just-perfection/quick-settings-night-light false
dconf write /org/gnome/shell/extensions/just-perfection/quick-settings-airplane-mode false


# }}}

