#!/usr/bin/env zsh
# Rebuild theming dist files and stage them for commit
# Usage:
# $ yarn run colors-build-and-stage  # Called by lint-staged
set -e

# Several lint-staged globs call this script in parallel. To prevent race
# conditions, we debounce it.
bin-debounce colors-build-and-stage || exit 0

colors-reload

git add \
  tools/term/zsh/config/theming/dist/ \
  tools/cli/bat/config/dist/ \
  tools/cli/rg/config/dist/ \
  tools/git/git/config/dist/
