#!/usr/bin/env zsh
# Test staged files for a given language
# Called by lint-staged via package.json
# Usage:
# $ precommit-test go /abs/path/to/file1.go /abs/path/to/file2.go
set -e

local lang=$1
shift

# No staged files to test
[[ $# -eq 0 ]] && exit 0

${lang}-test "$@"
