#!/usr/bin/env zsh
# Deploy rtk config to ~/.config/rtk
# Usage:
# $ tools/ai/rtk/deploy
set -e

CONFIG_DIR="${0:h}/config"
DEST_DIR=~/.config/rtk

mkdir -p $DEST_DIR
ln -fs \
  $CONFIG_DIR/filters.toml \
  $DEST_DIR/filters.toml
