#!/usr/bin/env bash
set -e

if ! which cargo &>/dev/null; then
  echo "⚠ cargo not found"
  echo "You need to install Rust first"
  exit 1
fi

# Installing dssim
cd ~/local/src
git clone git@github.com:pornel/dssim.git
cd ./dssim
cargo build --release
cd ~/local/bin
ln -fs ../src/dssim/target/release/dssim .

# Installing cjpeg-dssim
cd ~/local/src
git clone git@github.com:technopagan/cjpeg-dssim.git
cd ~/local/bin
ln -s ../src/cjpeg-dssim/cjpeg-dssim .
