#!/usr/bin/env bash

# We don't use the official gifsicle version as it seems unmaintained and lacks
# the lossy feature
cd ~/local/tmp
wget https://github.com/pornel/giflossy/releases/download/lossy%2F1.82.1/gifsicle-1.82.1-lossy.zip \
  -O ./giflossy.zip
unzip -j "./giflossy.zip" "linux/gifsicle-static" -d ~/local/bin
mv ~/local/bin/gifsicle-static ~/local/bin/gifsicle

# Converting terminal to gif
sudo apt-add-repository ppa:zanchey/asciinema
sudo apt-get update
sudo apt-get install asciinema
yarn add global asciicast2gif

