#!/usr/bin/env bash

sudo apt-get install jpegoptim

# Installing dssim
cd ~/local/src
git clone git@github.com:pornel/dssim.git
cd ./dssim
make
cd ~/local/bin
ln -fs ../src/dssim/bin/dssim .

# Installing cjpeg-dssim
cd ~/local/src
git clone git@github.com:technopagan/cjpeg-dssim.git
cd ~/local/bin
ln -s ../src/cjpeg-dssim/cjpeg-dssim .
