#!/usr/bin/env bash

# Installing jpegoptim from git as the version in Ubuntu does not allow piping
# to stdout, and thus cannot work with cjpeg-dssim
# https://github.com/tjko/jpegoptim/issues/6

cd ~/local/src
git clone git@github.com:tjko/jpegoptim.git

sudo apt-get install libjpeg-dev

cd jpegoptim
./configure --prefix="/home/$USER/local/"
make
make strip
make install

# Installing dssim
cd ~/local/src
git clone git@github.com:pornel/dssim.git
cd ./dssim
make
cd ~/local/bin
ln -fs ../src/dssim/bin/dssim .

# Installing cjpeg-dssim
cd ~/local/src
git clone git@github.com:technopagan/cjpeg-dssim.git
cd ~/local/bin
ln -s ../src/cjpeg-dssim/cjpeg-dssim .
