#!/usr/bin/env zsh

local repoRoot=${1:a}
local noeditFile=${0:a:h}/noedit
local allFiles

# We get the full list of tracked files
allFiles=(`find $repoRoot -type f`)

# We pipe the output to grep, to remove the binary files matching our pattern
local patterns="`cat $noeditFile | grep -v -e '^#' -e '^$'`"
patterns=(${(@f)patterns})
local grepCommand="grep --ignore-case --invert-match --extended-regexp "
for pattern in $patterns; do
	grepCommand=${grepCommand}" -e '${pattern}'"
done

echo $allFiles

eval "print -l $allFiles | $grepCommand"
