#!/usr/bin/env zsh
# This script is called by CtrlP when in a git repo.
# This will return the list of tracked files, excluding the one deleted in the
# working directory, but including the newly created files. This will also
# ignore files ignored by git as well as binary files defined in the ./noedit
# file.

local repoRoot=${1:a}
local deletedFiles addedFiles lsFiles

# We first get the list of common excluded patterns from the ./nodedit file
local patterns="`cat ${0:a:h}/noedit | grep -v -e '^#' -e '^$'`"
patterns=(${(@f)patterns})

# Building the grep pipe arguments
local grepArgs=" -e 'js'"
for pattern in $patterns; do
	# grepArgs=${grepArgs}" -e '${pattern}'"
done

# We get the full list of tracked files
cd $repoRoot
lsFiles=(`git ls-files`)

# We then remove the list of deleted files from it
deletedFiles=(`git diff --name-only --diff-filter=D`)
lsFiles=( "${lsFiles[@]/$deletedFiles}" )

# We then add the list of new files to it
addedFiles=(`git ls-files --others --exclude-standard`)
lsFiles+=($addedFiles)

# We pipe the output to grep, to remove the binary files matching our pattern
print -l $lsFiles
