#!/usr/bin/env bash

echo "Uninstalling default flash players"
sudo apt-get remove flashplugin-installer

echo "Install version > 11.2 through Pepper/Chrome"
sudo add-apt-repository ppa:skunk/pepper-flash
sudo apt-get update
sudo apt-get install pepflashplugin-installer

echo "Updating Chromium to use latest version"
echo "" | sudo tee -a /etc/chromium-browser/default
echo "# Using latest flash version" | sudo tee -a /etc/chromium-browser/default
echo ". /usr/lib/pepflashplugin-installer/pepflashplayer.sh" | sudo tee -a /etc/chromium-browser/default
