#!/usr/bin/env zsh

npm install -g gifify

# Installing gifsicle from a git fork as it includes a lossy feature
cd /tmp
wget https://github.com/pornel/giflossy/releases/download/lossy%2F1.82.1/gifsicle-1.82.1-lossy.zip \
  -O ./giflossy.zip

unzip -j "./giflossy.zip" "linux/gifsicle-static" -d ~/local/bin
mv ~/local/bin/gifsicle-static ~/local/bin/gifsicle

