#!/usr/bin/env bash
# kazam: Screen recording, with embedded webcam
# https://github.com/henrywoo/kazam

# Dependencies
sudo apt install \
	build-essential \
	libpython3-dev \
	libdbus-1-dev \
	libcairo2-dev \
	libgirepository1.0-dev \
	gir1.2-gudev-1.0 \
	gir1.2-keybinder-3.0

pip install kazam
