#!/usr/bin/env zsh
set -e

# Load color definitions
colors-load-definitions

# Fake values for debuging, or values coming from stdin
if [[ "$1" == "--dry-run" ]]; then
  local modelName="Sonnet 4.6"
  local currentDir=~/.oroshi/
  local totalCost=0
  local totalTokens=51000
  local contextPercentage=24
  local sessionId="deadbeef-0000-ffff-cccc-1234567890ab"
else
  local stdinData=$(cat)
  local currentDir=$(echo "$stdinData" | jq -r '.workspace.current_dir')
  local modelName=$(echo "$stdinData" | jq -r '.model.display_name')
  local totalCost=$(echo "$stdinData" | jq -r '.cost.total_cost_usd // 0 | . * 10000 | round / 10000')
  local totalTokens=$(echo "$stdinData" | jq -r '.context_window.current_usage | (.input_tokens + .output_tokens + .cache_creation_input_tokens + .cache_read_input_tokens)')
  local contextPercentage=$(echo "$stdinData" | jq -r '.context_window.used_percentage // 0')
  local sessionId=$(echo "$stdinData" | jq -r '.session_id // ""')
fi

local statusline=()

# Unused info {{{
# Model (effort)
# local settingsFile=~/.claude/settings.json
# local effortLevel=$(jq -r '.effortLevel // "medium"' "$settingsFile")
# }}}

# Context Badge
local displayBadge="$(context-badge "$currentDir")"
[[ "$displayBadge" != "" ]] && statusline+=("$displayBadge ")

# Context budget
local tokensKRaw=$(printf "%.1f" $((totalTokens / 1000.0)))
local tokensK="${tokensKRaw%\.0}k"
local contextColor=$COLORS[claude-contextHigh]
((contextPercentage < 60)) && contextColor=$COLORS[claude-contextMedium]
((contextPercentage < 20)) && contextColor=$COLORS[claude-contextLow]
local displayContext="$(colorize "${tokensK}" $contextColor)"
statusline+=("$displayContext ")

# Cost
local isInCents=$((totalCost < 1))
if [[ $isInCents == "1" ]]; then
  local roundedCents=$((totalCost * 100 + 0.5))
  local displayCost="$(colorize "${roundedCents%.*}¢" $COLORS[claude-costLow])"
else
  local roundedDollars=$(printf "$%.2f" "$totalCost")
  local displayCost="$(colorize "${roundedDollars}" $COLORS[claude-costHigh])"
fi
statusline+=("$displayCost ")

# Model
local displayModel="$(colorize "${modelName}" $COLORS[claude-model])"
statusline+=("$displayModel ")

# Session ID
local displaySession="$(colorize "[${sessionId}]" $COLORS[claude-sessionId])"
statusline+=("$displaySession")

print "${(j::)statusline}"
