#!/usr/bin/env bash
# Easy download/upload of files from Rapidshare and co

cd ~/local/src
git-directory-sync git@github.com:mcrapet/plowshare.git

cd ./plowshare
make install PREFIX=/home/$USER/local

rehash
plowmod --install
