#!/usr/bin/env bash

echo "Downloading binary"
wget https://yt-dl.org/downloads/2015.05.04/youtube-dl \
	-O ~/local/bin/youtube-dl

echo "Make it executable"
chmod +x ~/local/bin/youtube-dl

echo "Update the script"
~/local/bin/youtube-dl -U

