#!/usr/bin/env bash
set -ex

sudo apt-get install virtualbox

# Kubectl
sudo snap install kubectl --classic

# Minikube
cd ~/local/bin
wget \
  https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
  -O minikube
chmod +x ./minikube
