#!/usr/bin/env zsh
# gh is the official GitHub CLI.
# It replaces hub, and the deprecated yarn gh tool
# https://cli.github.com/
set -e

local DOWNLOAD_URL="https://github.com/cli/cli/releases/download/v2.70.0/gh_2.70.0_linux_amd64.deb"
local LOCAL_DEB="gh.deb"

# Install gh
cd ~/local/tmp
wget "$DOWNLOAD_URL" -O "./$LOCAL_DEB"
install-deb "./$LOCAL_DEB"

# install completion
gh completion --shell zsh \
  > ~/.oroshi/config/term/zsh/completion/compdef/_gh

# authenticate to GH
gh auth login
