#!/usr/bin/env bash
# gh is the official GitHub CLI.
# It replaces hub, and the deprecated yarn gh tool
# https://cli.github.com/
set -e

DOWNLOAD_URL="https://github.com/cli/cli/releases/download/v2.20.2/gh_2.20.2_linux_386.deb"
LOCAL_DEB="gh.deb"

cd ~/local/tmp
wget "$DOWNLOAD_URL" -O "./$LOCAL_DEB"
install-deb "./$LOCAL_DEB"

echo "Now, authenticate using the web browser"
/usr/bin/gh auth login

# Adding zsh autocompletion
/usr/bin/gh completion -s zsh |
	sudo tee /usr/local/share/zsh/site-functions/_gh
