#!/usr/bin/env bash
# Git Large File Storage
# https://git-lfs.com/
set -e

curl -s \
	https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh |
	sudo bash

sudo apt-get install git-lfs
