#!/usr/bin/env zsh

CONFIG_DIR="${0:h}/config"
DEST_DIR=~/.config/nvim

# Create config file
mkdir -p $DEST_DIR
ln \
	-fns $CONFIG_DIR/init.lua \
	$DEST_DIR/init.lua

# Create runtime directories
mkdir -p $DEST_DIR/swap
mkdir -p $DEST_DIR/undo
mkdir -p $DEST_DIR/view
