#!/usr/bin/env zsh
# Parses the return of a fzf multi-selection
local input="$@"

# Stop early
[[ $input == "" ]] && exit

# Sanitize selection
local files=()
for line in ${(f)input}; do
  local split=(${(@s/   /)line})

  local filepath="$split[1]"
  filepath=${filepath:q}
  filepath=${~filepath}

  files+=($filepath)
done

echo $files

