#!/usr/bin/env zsh
# ImageMagick config
# Default ImageMagick config has low default values for memory management,
# making it fail when converting large files
# We are using a custom policy that should fix it

local CONFIG_DIR=~/.oroshi/config/image/imagemagick

sudo cp \
	$CONFIG_DIR/policy.xml \
	/etc/ImageMagick-6/
