#!/usr/bin/env zsh
# CLI for fly.io
# Hosting and running of Docker images
# https://github.com/superfly/flyctl

# Install fly in custom dir
export FLYCTL_INSTALL=~/local/etc/flyctl
mkdir $FLYCTL_INSTALL

curl -L https://fly.io/install.sh | sh

# Make global symlink
ln -fs $FLYCTL_INSTALL/bin/flyctl ~/local/bin/fly
