#!/usr/bin/env zsh
# Regenerate ./dist/oroshi.json from ./src/oroshi.json
# Usage:
# $ tools/ai/claude/config/themes/generate-theme
set -e

local currentDir=${0:a:h}

mkdir -p $currentDir/dist

colors-template-render \
  $currentDir/src/oroshi.json \
  >$currentDir/dist/oroshi.json
