#!/usr/bin/env zsh
# Regenerate ~/.claude/themes/oroshi.json from ./src/oroshi.json
# Usage:
# $ tools/ai/claude/config/themes/generate-theme
set -e

local currentDir=${0:a:h}

mkdir -p ~/.claude/themes

colors-template-render \
  $currentDir/src/oroshi.json \
  >~/.claude/themes/oroshi.json
