# [f]iles
alias vfR='git rm -r'
alias vfa='git-file-add'
alias vfd='git-file-diff'
alias vfds='git-file-diff --staged'
alias vffc='git-file-fix-conflicts'
alias vfforget='git rm --cached -r'
alias vfr='git-file-untrack'
alias vfh='fzf-git-file-history'
alias vfl='git-file-list-dirty'
alias vfls='git-file-list-staged'
alias vflu='git-file-list-stageable'
alias vfmv='git mv'
alias vfresurrect='git-file-resurrect'
alias vfrevert='git-file-revert'
alias vfua='git-file-unstage-all'
alias vfu='git-file-unstage'
