# [t]ags
alias vtR='git-tag-remove'
alias vtc='git-tag-create'
alias vtlr='git-tag-list-remote'
alias vtl='git-tag-list'
alias vtpl='git fetch --tags'
alias vtps='git-tag-push'
alias vts='git-tag-switch'
alias vt.a='git-tag-current-all'
alias vt.='git-tag-current'
alias vt?='git-tag-exists'
