#!/usr/bin/env zsh
# Build the git-branch-push-pretty binary
# Usage:
# $ build
set -e
setopt local_options err_return

local binaryName="git-branch-push-pretty"
local srcDirectory="${OROSHI_ROOT}/scripts/src/${binaryName}"

go build \
  -o "${srcDirectory}/dist/${binaryName}" \
  "${srcDirectory}"
