#!/usr/bin/env zsh
# Windows machine in the cloud, great for gaming
# https://shadow.tech/
set -e

local DOWNLOAD_URL="https://update.shadow.tech/launcher/prod/linux/x86_64/shadow-amd64.deb"

cd ~/local/tmp
wget $DOWNLOAD_URL -O shadow.deb
sudo dpkg -i ./shadow.deb
sudo apt-get -f install
