#!/usr/bin/env zsh
# Steam: Game library
set -e

local DOWNLOAD_URL="https://cdn.cloudflare.steamstatic.com/client/installer/steam.deb"

# Download and install
cd ~/local/tmp
wget $DOWNLOAD_URL -O steam.deb
install-deb ./steam.deb

# Update deps
sudo dpkg --add-architecture i386
sudo apt update
sudo apt install wget gdebi-core libgl1-mesa-dri:i386 libgl1-mesa-glx:i386
sudo apt upgrade
