#!/usr/bin/env zsh
# dssim: Calculate image dissimilarity score between two images
# https://github.com/kornelski/dssim
set -e

local DOWNLOAD_URL="https://github.com/kornelski/dssim/releases/download/3.2.3/dssim_3.2.3_amd64.deb"

cd ~/local/tmp
wget $DOWNLOAD_URL -O dssim.deb

install-deb ./dssim.deb
rm ./dssim.deb
