source ~/.config/nvim/includes/functions/CloseBufferByFilepath.vim
source ~/.config/nvim/includes/functions/Colorize.vim
source ~/.config/nvim/includes/functions/ConvertLineEndingToUnix.vim
source ~/.config/nvim/includes/functions/ConvertLineEndingsToDos.vim
source ~/.config/nvim/includes/functions/ConvertToUTF8.vim
source ~/.config/nvim/includes/functions/ConvertWindowsCharacters.vim
source ~/.config/nvim/includes/functions/Debug.vim
source ~/.config/nvim/includes/functions/DeleteCurrentFile.vim
source ~/.config/nvim/includes/functions/FiletypeKey.vim
source ~/.config/nvim/includes/functions/FixEpub.vim
source ~/.config/nvim/includes/functions/GetNpmRoot.vim
source ~/.config/nvim/includes/functions/GitRoot.vim
source ~/.config/nvim/includes/functions/IndentLevel.vim
source ~/.config/nvim/includes/functions/IndentWithSpaces.vim
source ~/.config/nvim/includes/functions/IndentWithTabs.vim
source ~/.config/nvim/includes/functions/JavaScriptIsZx.vim
source ~/.config/nvim/includes/functions/Lint.vim
source ~/.config/nvim/includes/functions/NextNonBlankLine.vim
source ~/.config/nvim/includes/functions/RemoveTrailingSpaces.vim
source ~/.config/nvim/includes/functions/RunCurrentFile.vim
source ~/.config/nvim/includes/functions/SeemsLatin1InUTF8.vim
source ~/.config/nvim/includes/functions/ShellEscapeForDoubleQuotes.vim
source ~/.config/nvim/includes/functions/StrDebug.vim
source ~/.config/nvim/includes/functions/StrLength.vim
source ~/.config/nvim/includes/functions/StrTrim.vim
source ~/.config/nvim/includes/functions/StrUncomment.vim
source ~/.config/nvim/includes/functions/YamlIsGitHubActions.vim
