#!/usr/bin/env zsh
# Returns raw list of available bats test names
# Usage:
# $ bats-test-list-raw
# Output:
#   testName▮/full/path/to/test.bats
TESTS_DIR=~/.oroshi/scripts/bin/__tests__

for testFile in $TESTS_DIR/*.bats(N); do
  echo "${testFile:t:r}▮${testFile:a}"
done
