#!/usr/bin/env zsh

local tarlink=http://cardpeek.googlecode.com/files/cardpeek-0.8.tar.gz
local tarfile=/usr/local/etc/cardpeek-0.8.tar.gz
local cardpeekdir=/usr/local/etc/cardpeek

echo "Installing dependencies"
sudo apt-get install libglib2.0-dev
sudo apt-get install libgtk-3-dev
sudo apt-get install libpcsclite-dev
sudo apt-get install liblua5.2-dev
sudo apt-get install pcscd # Needed to start the daemon


cd /usr/local/etc/
wget $tarlink
tar xvzf $tarfile
rm $tarfile
mv ./cardpeek-0.8 $cardpeekdir

cd $cardpeekdir
./configure
./make

ln -s /usr/local/bin/cardpeek /usr/local/etc/cardpeek/cardpeek
