#!/usr/bin/env bash

yarn global add textlint
yarn global add textlint-rule-common-misspellings
yarn global add textlint-rule-editorconfig
yarn global add textlint-rule-write-good
yarn global add textlint-rule-alex
