#!/usr/bin/env bash
echo "Installing tomate"
RELEASE=$(sed -n 's/VERSION_ID="\(.*\)"/\1/p' /etc/os-release)
wget -O- "http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_$RELEASE/Release.key" | sudo apt-key add -
sudo bash -c "echo 'deb http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_$RELEASE/ ./' > /etc/apt/sources.list.d/tomate.list"
sudo apt-get update 

sudo apt-get install tomate-gtk \
                     tomate-notify-plugin \
                     tomate-alarm-plugin \
                     tomate-launcher-plugin \
                     tomate-indicator-plugin
