#!/usr/bin/env zsh
# Flameshot: Take screenshots

CONFIG_DIR="$(dirname "$0")/config"
DEST_DIR=~/.config/flameshot

mkdir -p $DEST_DIR
ln \
	-fs \
	$CONFIG_DIR/flameshot.ini \
	$DEST_DIR/flameshot.ini
