# JavaScript
# Yarn {{{
alias yR='yarn remove'
alias yad='yarn add --dev -- '
alias yadf='yarn add --dev -W -- '
alias yagR='yarn global remove'
alias yag='yarn global add -- '
alias ya='yarn add -- '
alias yaf='yarn add -W -- '
alias ygR='yarn global remove'
alias yga='yarn global add -- '
alias y='yarn'
alias yF='yarn --force'
alias yi='yarn init'
alias yrb='yr build'
alias yrbw='yr build:watch'
alias yrbp='yr build:prod'
alias yrc='yr consolidate'
alias yrdb='yr docs:build'
alias yrdbp='yr docs:build:prod'
alias yrds='yr docs:serve'
alias yrdd='yr docs:deploy'
alias yrlb='yr lambda:build'
alias yrlbw='yr lambda:build:watch'
alias yrls='yr lambda:serve'
alias yrtm='yr test:manual'
alias yrtv='yr test:visual'
alias yrtva='yr test:visual:approve'
alias yrd='yr deploy'
alias yrlf='yr lint:fix'
alias yrljs='yr lint:js'
alias yrljson='yr lint:json'
alias yrlc='yr lint:css'
alias yrlm='yr lint:md'
alias yrlmf='yr lint:md:fix'
alias yrlh='yr lint:html'
alias yrl='yr lint'
alias yrpb='yr playground:build'
alias yrps='yr playground:serve'
alias yrp='yr push'
alias yrpn='yr post:new'
alias yrr='vbpl && yr release'
alias yrrp='yrr patch'
alias yrrmi='yrr minor'
alias yrrma='yrr major'
alias yrs='yr serve'
alias yrw='yr watch'
alias yl?='yarn-has-links'
alias yw='yarn why'
alias ysd='emma -D'
alias ys='emma'
alias yug='yarn global upgrade'
alias yuF='yu --force'
alias ypc='depcheck . --ignore-dirs=dist,tmp,build --specials=eslint,webpack,babel --ignores=husky,jest'
# }}}
# nvm {{{
alias nvs='nvm use'
alias nvu='nvm use'
alias nvud='nvm use default'
alias nvl='nvm list'
alias nvd='nvm version default'
alias nvc='nvm current'
# }}}

alias jsmin="uglifyjs"
