# Yarn

# Global packages
# 	Add
alias yag='yarn-global-add'
alias yga='yarn-global-add'
# 	Remove
alias yagR='yarn-global-remove'
alias yRg='yarn-global-remove'
alias ygR='yarn-global-remove'
# 	List
alias ygl='yarn-global-list'
alias ydlg='yarn-global-list'
# 	Upgrade
alias yug='yarn global upgrade'

# Local dependencies
alias yR='yarn remove'
alias yadf='yarn-dependency-add-dev-root'
alias yad='yarn-dependency-add-dev'
alias yaf='yarn-dependency-add-root'
alias ya='yarn-dependency-add'
alias ydla='yarn-dependency-list --all'
alias ydld='yarn-dependency-list --dev'
alias ydl='yarn-dependency-list'
alias yuF='yu --force'
alias yu='yarn-dependency-update'
alias yw='yarn-dependency-why'

# Linked packages
alias ylRa='yarn-link-remove-all'
alias ylRg='yarn-link-remove-global'
alias ylR='yarn-link-remove'
alias yllg='yarn-link-list --global'
alias yllr='yarn-link-list-raw'
alias yll='yarn-link-list'
alias ylr='yarn-link-reload'
alias yl='yarn-link'

# Scripts
alias yrbp='yr build:prod'
alias yrbw='yr build:watch'
alias yrb='yr build'
alias yrc='yr consolidate'
alias yrdbp='yr docs:build:prod'
alias yrdb='yr docs:build'
alias yrdd='yr docs:deploy'
alias yrds='yr docs:serve'
alias yrd='yr deploy'
alias yrlbw='yr lambda:build:watch'
alias yrlb='yr lambda:build'
alias yrlf='yarn-run-lint --fix'
alias yrls='yr lambda:serve'
alias yrl='yarn-run-lint'
alias yrpb='yr playground:build'
alias yrpn='yr post:new'
alias yrps='yr playground:serve'
alias yrp='yr push'
alias yrrma='yrr major'
alias yrrmi='yrr minor'
alias yrrp='yrr patch'
alias yrr='vbpl && yr release'
alias yrs='yr serve'
alias yrtm='yr test:manual'
alias yrtva='yr test:visual:approve'
alias yrtv='yr test:visual'
alias yrtw='yr test:watch'
alias yrt='yr test'
alias yrw='yr watch'
alias yr='yarn-run'
alias ys?='yarn-script-exists'
alias yslr='yarn-script-list-raw'
alias ysl='yarn-script-list'

# Misc
alias yF='yarn --force'
alias yi='yarn-init'
alias ypu='yarn-policies-update'
alias ysd='emma -D'
alias ys='emma'
alias y='yarn'
