# Yarn

# Local dependencies
alias yR='yarn-dependency-remove'
alias yRd='yarn-dependency-remove-dev'
alias yadf='yarn-dependency-add-dev-root'
alias yad='yarn-dependency-add-dev'
alias yaf='yarn-dependency-add-root'
alias ya='yarn-dependency-add'
alias ydla='yarn-dependency-list --all'
alias ydld='yarn-dependency-list --dev'
alias ydl='yarn-dependency-list'
alias yuF='yu --force'
alias yu='yarn-dependency-update'
alias yw='yarn-dependency-why'

# Linked packages
alias ylR='yarn-link-remove'
alias yllr='yarn-link-list-raw'
alias yll='yarn-link-list'
alias yl='yarn-link'

alias ylaberlaas='yarn-link /home/tim/local/www/projects/aberlaas/modules/lib'
alias ylesmify='yarn-link /home/tim/local/www/projects/esmify/lib'
alias ylfirost='yarn-link /home/tim/local/www/projects/firost/lib'
alias ylgilmore='yarn-link /home/tim/local/www/projects/gilmore/lib'
alias ylgolgoth='yarn-link /home/tim/local/www/projects/golgoth/lib'

# Linked packages (Classic)
alias ylcl='yarn-link-classic-list'
alias ylcc='yarn-link-classic-create'
alias ylc?='yarn-link-classic-exists'
alias ylcR='yarn-link-classic-remove'
alias ylc+='yarn-link-classic-enable'
alias ylc-='yarn-link-classic-disable'

# Scripts
alias yrbp='yr build:prod'
alias yrbw='yr build:watch'
alias yrb='yr build'
alias yrc='yr consolidate'
alias yrdbp='yr docs:build:prod'
alias yrdb='yr docs:build'
alias yrdd='yr docs:deploy'
alias yrds='yr docs:serve'
alias yrd='yr deploy'
alias yrlbw='yr lambda:build:watch'
alias yrlb='yr lambda:build'
alias yrlf='yarn-run-lint-fix'
alias yrls='yr lambda:serve'
alias yrl='yarn-run-lint'
alias yrpb='yr playground:build'
alias yrpn='yr post:new'
alias yrps='yr playground:serve'
alias yrp='yr push'
alias yrrma='yrr major'
alias yrrmi='yrr minor'
alias yrrp='yrr patch'
alias yrr='vbpl && yr release'
alias yrs='yr serve'
alias yrtm='yr test:manual'
alias yrtva='yr test:visual:approve'
alias yrtv='yr test:visual'
alias yrtw='yarn-run-test-watch'
alias yrt='yarn-run-test'
alias yrtff='yarn-run-test --failFast'
alias yrw='yr watch'
alias yr='yarn-run'
alias ys?='yarn-script-exists'
alias yslr='yarn-script-list-raw'
alias ysl='yarn-script-list'

# Misc
alias yF='yarn --force'
alias yi='yarn-init'
alias ypu='yarn-policies-update'
alias ysd='emma -D'
alias ys='emma'
alias y='yarn'
