# Custom shell tools, like nvm, rvm, etc
require 'tools/bat.zsh'
require 'tools/direnv.zsh'
require 'tools/exa.zsh'
require 'tools/fzf.zsh'
require 'tools/gvm.zsh'
require 'tools/ls.zsh'
require 'tools/nvm.zsh'
require 'tools/pyenv.zsh'
require 'tools/rg.zsh'
require 'tools/z.zsh'
require 'tools/zsh.zsh'
