return {
}
--   -- https://github.com/nvim-telescope/telescope.nvim
--   "nvim-telescope/telescope.nvim",
--   branch = "0.1.x",
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--     "nvim-treesitter/nvim-treesitter",
--     { "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
--     "nvim-tree/nvim-web-devicons",
--   },
--   config = function()
--     local telescope = require("telescope")
--     local actions = require("telescope.actions")
--     local action_state = require("telescope.actions.state")
--     local builtin = require("telescope.builtin")
--
--     -- CTRL-P: {{{
--     -- Find files in project
--     local function onCtrlP()
--       local gitRoot = vim.fn.systemlist("git-directory-root")[1]
--       builtin.find_files({
--         cwd = gitRoot
--       })
--     end
--     nmap('<C-P>', onCtrlP, "Find files in project")
--     imap('<C-P>', onCtrlP, "Find files in project")
--     -- }}}
--
--     -- CTRL-T: {{{
--     -- Find files in current directory
--     local function onCtrlT()
--       builtin.find_files({
--         cwd = vim.fn.expand('%:p:h')
--       })
--     end
--     nmap('<C-T>', onCtrlT, "Find files in current directory")
--     imap('<C-T>', onCtrlT, "Find files in current directory")
--     nmap('Ⓟ', onCtrlT, "Find files in current directory")
--     imap('Ⓟ', onCtrlT, "Find files in current directory")
--     -- }}}
--
--
--     -- CTRL-L: {{{
--     -- Clear the prompt
--     local function clearPrompt(prompt_bufnr)
--       local current_picker = action_state.get_current_picker(prompt_bufnr)
--       current_picker:reset_prompt()
--     end
--     --- }}}
--
--     -- ENTER: {{{
--     -- Open file in new tab
--     local function openFileInNewTab(prompt_bufnr)
--       local selection = action_state.get_selected_entry()
--       actions.close(prompt_bufnr)
--
--       local fullPath = vim.fs.joinpath(selection.cwd, selection.value)
--       vim.cmd('tab drop ' .. fullPath)
--     end
--
--     telescope.setup({
--       defaults = {
--         layout_strategy = 'horizontal',
--         layout_config = {
--           prompt_position = 'top',
--           height = 999,
--           width = 999,
--           preview_width = 0.5
--         },
--
--         path_display = { "smart" },
--
--         mappings = {
--           i = {
--             ["<CR>"] = openFileInNewTab,
--             ["<C-l>"] = clearPrompt, -- Clear prompt
--             ["<C-d>"] = actions.close, -- Close
--
--             ["<C-k>"] = actions.move_selection_previous, -- Up
--             ["<C-j>"] = actions.move_selection_next, -- Down
--
--             ["Ⓚ"] = actions.preview_scrolling_up, -- Preview up
--             ["Ⓙ"] = actions.preview_scrolling_down, -- Preview down
--
--           },
--         },
--       },
--     })
--
--     telescope.load_extension("fzf")
--   end,
-- }
