return {
  -- -- https://github.com/folke/which-key.nvim
  -- -- Displays configured keys
  -- -- Not yet sure how useful this can be, but seem to be usable to show a list
  -- -- of all marks and registers (clipboards) as well as spelling suggestions
  -- -- Not sure if very useful
  -- "folke/which-key.nvim",
  -- event = "VeryLazy",
  -- init = function()
  --   -- vim.o.timeout = true
  --   -- vim.o.timeoutlen = 500
  -- end,
  -- opts = {
  --   -- your configuration comes here
  --   -- or leave it empty to use the default settings
  --   -- refer to the configuration section below
  -- },
  -- keys = {
  --   {
  --     "?",
  --     function()
  --       require("which-key").show({ 
  --         global = true,
  --         loop = true
  --       })
  --     end,
  --     desc = "Buffer Local Keymaps (which-key)",
  --   },
  -- },
}
