
export FZF_DEFAULT_OPTS=""
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --color fg:$COLOR[gray3]"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --color bg:$COLOR[black]"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --color hl:$COLOR[red5]"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --color fg+:$COLOR[black]"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --color bg+:$COLOR[red5]"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --color hl+:$COLOR[white]"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --color info:$COLOR[yellow]"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --color prompt:$COLOR[white]"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --color pointer:$COLOR[white]"
