# ls
alias la="better-ls --all"
alias la@="ls --all --extended --long"
alias lsd="better-ls --only-dirs"
alias ls="better-ls"
alias l@a="la@"
alias l@="better-ls --long --extended"
alias ms="better-ls"
alias sl="better-ls"
alias s="better-ls"
