import json
# from tab_bar_modules.colors import getCursorColor
ALL_PROJECTS = {}

def getProjectData(projectName):
    return ALL_PROJECTS.get(projectName, {})


# Set the ALL_PROJECTS object, that contains name, icons and colors of all
# projects
def initProjectList():
    global ALL_PROJECTS

    # This file is automatically generated from its sister projects.zsh in the
    # same folder
    jsonPath = "/home/tim/.oroshi/config/term/zsh/theming/env/projects.json"
    rawProjectData = json.load(open(jsonPath, "r"))

    # First, build an object with one key per project, by reading the _NAME
    # variables
    for key, value in rawProjectData.items():
        # Keep only name keys (ending with _NAME, but not FOREGROUND_NAME nor
        # BACKGROUND_NAME)
        if not (key.endswith("_NAME") and not key.endswith("GROUND_NAME")):
            continue

        projectName = value
        projectPrefix = key.replace("_NAME", "")
        ALL_PROJECTS[projectName] = {"__prefix": projectPrefix}

    # Fill each entry with icon and colors
    for _, projectData in ALL_PROJECTS.items():
        projectPrefix = projectData["__prefix"]

        # Icon
        projectData["icon"] = rawProjectData.get(f"{projectPrefix}_ICON")

        # Background
        projectBgRaw = rawProjectData.get(f"{projectPrefix}_BACKGROUND", None)
        # if projectBgRaw:
        #     projectData["bg"] = getCursorColor(projectBgRaw)

        # Background inactive
        projectBgInactiveRaw = rawProjectData.get(f"{projectPrefix}_BACKGROUND_INACTIVE", None)
        # if projectBgInactiveRaw:
        #     projectData["bgInactive"] = getCursorColor(projectBgInactiveRaw)

        # Foreground
        projectFgRaw = rawProjectData.get(f"{projectPrefix}_FOREGROUND", None)
        # if projectFgRaw:
        #     projectData["fg"] = getCursorColor(projectFgRaw)
