function git-env-update() {
  gitstatus_query 'OROSHI'

  # Get all available vars with typeset -m 'VCS_STATUS_*'

  # Are we in a git directory?
  export GIT_DIRECTORY_IS_REPOSITORY="0"
  [[ $VCS_STATUS_RESULT == "ok-sync" ]] && GIT_DIRECTORY_IS_REPOSITORY="1"
  export GIT_DIRECTORY_ROOT=$VCS_STATUS_WORKDIR
  export GIT_DIRECTORY_HAS_STAGED_FILES=$VCS_STATUS_HAS_STAGED
  export GIT_DIRECTORY_IS_DIRTY="0"
  (( $VCS_STATUS_HAS_UNSTAGED )) && GIT_DIRECTORY_IS_DIRTY="1"
  (( $VCS_STATUS_HAS_UNTRACKED )) && GIT_DIRECTORY_IS_DIRTY="1"

  export GIT_BRANCH_CURRENT=$VCS_STATUS_LOCAL_BRANCH
  export GIT_COMMIT_CURRENT=$VCS_STATUS_COMMIT
  export GIT_REMOTE_CURRENT=$VCS_STATUS_REMOTE_NAME
  export GIT_REMOTE_URL=$VCS_STATUS_REMOTE_URL

  export GIT_STASH_EXISTS=$VCS_STATUS_STASHES

  export GIT_DIRECTORY_IS_GITHUB="0"
  [[ $VCS_STATUS_REMOTE_URL == *github.com* ]] && GIT_DIRECTORY_IS_GITHUB="1"
}
