#!/usr/bin/env zsh
# Given a tab/session name, will return an icon from the font

local name=$1
local icon=''
[[ $name == 'aberlaas' ]] && icon=''
[[ $name == 'aoinan' ]]   && icon=' '
[[ $name == 'bg' ]]       && icon='力'
[[ $name == 'books' ]]    && icon=' '
[[ $name == 'comics' ]]   && icon='X'
[[ $name == 'dropbox' ]]  && icon=''
[[ $name == 'firost' ]]   && icon='❯ '
[[ $name == 'golgoth' ]]   && icon=' '
[[ $name == 'movies' ]]   && icon=' '
[[ $name == 'music' ]]    && icon=' '
[[ $name == 'norska' ]]   && icon='煮'
[[ $name == 'oroshi' ]]   && icon='x '
[[ $name == 'perso' ]]    && icon=''
[[ $name == 'pictures' ]] && icon=' '
[[ $name == 'projects' ]] && icon=''
[[ $name == 'reddinx' ]]  && icon=' '
[[ $name == 'roleplay' ]] && icon='ﲅ'
[[ $name == 'sov' ]]      && icon='蠟'
[[ $name == 'tmp' ]]      && icon='זּ '
[[ $name == 'twitter' ]]  && icon=' '
[[ $name == 'videos' ]]   && icon=' '
[[ $name == 'vim' ]]      && icon=' '
[[ $name == 'www' ]]      && icon=''
[[ $name == 'zsh' ]]      && icon=' '

echo $icon
