#!/usr/bin/env zsh
# Given a session type, return its color

local session_name=$1
local session_color='colour136'

[[ $session_name == 'algolia' ]] && session_color='colour24'
[[ $session_name == 'bg' ]] && session_color='colour202'
[[ $session_name == 'perso' ]] && session_color='colour141'
[[ $session_name == 'projects' ]] && session_color='colour35'
[[ $session_name == 'tmp' ]] && session_color='colour233'

echo $session_color
