#!/usr/bin/env zsh

local output=''

# Dropbox status {{{
local dropbox_status=''
dropbox_status=`dropbox status`
if [[ $dropbox_status == "Dropbox isn't running!" ]]; then
  output="#[fg=colour160] #[default] $output"
else
  output=" $output"
fi
# }}}
# Clock {{{
local clock="$(date +'%d/%m %H:%M')"
output=" $clock $output"
# }}}
# Connection status {{{
local connection_status=''
if is-online; then
  local ping="$(ping-average)"
  [[ $ping -lt 230 ]] && connection_status="#[fg=colour160] ${ping}ms#[default]"
  [[ $ping -lt 160 ]] && connection_status="#[fg=colour136] ${ping}ms#[default]"
  [[ $ping -lt 80 ]] && connection_status="#[fg=colour35] ${ping}ms#[default]"
else
  connection_status='#[fg=colour160,bold]  offline!#[default]'
fi
output="$connection_status $output"
# }}}
# Kubernetes context {{{
# Commenting out the part about Kubernetes as I won't be using it again soon
# if [ $commands[kubectl] ]; then
#   local currentContext="$(kubectl config current-context)"
#   if [[ $currentContext == "minikube" ]]; then
#     local minikubeStatus="$(minikube status --format "{{.MinikubeStatus}}")"
#   fi

#   if [[ $currentContext == "minikube" && $minikubeStatus == "Running" ]]; then
#     output="#[fg=colour35]☸ #[default] $output"
#   fi
#   if [[ $currentContext == "minikube" && $minikubeStatus == "Stopped" ]]; then
#     output="#[fg=colour241]☸ #[default] $output"
#   fi
#   if [[ $currentContext =~ "^gke" ]]; then
#     output="#[fg=colour69]☸ #[default] $output"
#   fi
# fi
# }}}
# Battery life {{{
# Do not display if full
# Display in green if charging
# Display in grey, yellow and red when level drops
local battery_status="$(battery-status)"
local battery_percent="$(battery-percent)"
local battery_duration="$(battery-duration)"
if [[ $battery_percent -ne 99 ]]; then
  local battery_display="${battery_percent}%"
  if [[ $battery_status == 'discharging' ]]; then
    battery_display="${battery_display} (${battery_duration})"
  fi
  # Charging, green
  if [[ $battery_status == 'charging' ]]; then
     output="#[fg=colour35] $battery_display#[default] $output"
  else
    if [[ $battery_percent -lt 100 && $battery_percent -ge 50 ]]; then
      output=" $battery_display $output"
    fi
    if [[ $battery_percent -lt 50 && $battery_percent -ge 10 ]]; then
      output="#[fg=colour136] $battery_display#[default] $output"
    fi
    if [[ $battery_percent -lt 10 ]]; then
      output="#[fg=colour160,bold] $battery_display#[default] $output"
    fi
  fi
fi
# }}}

# Currently playing {{{
local currently_playing=''
if spotify-is-running; then
  currently_playing="$(spotify-data)"
  if [ "${#currently_playing}" -gt 40 ]; then
    currently_playing="$(echo $currently_playing | cut -c 1-40)…"
  fi
  currently_playing="#[fg=colour35] $currently_playing#[default]"
else if cmus-is-running; then
  currently_playing="$(cmus-data title)"
  local music_status="$(cmus-data status)"
  # Adding play/pause icon
  if [[ $music_status == 'playing' ]]; then
    currently_playing=" $currently_playing"
  else
    currently_playing=" $currently_playing"
  fi
  # Adding shuffle icon
  if [[ "$(cmus-data shuffle)" == "true" ]]; then
    currently_playing=" $currently_playing"
  fi
  # Adding color
  if [[ $music_status == 'playing' ]]; then
    currently_playing="#[fg=colour69]$currently_playing#[default]"
  else
    currently_playing="#[fg=colour241]$currently_playing#[default]"
  fi
fi
fi
output="$currently_playing $output"

echo $output
