#!/usr/bin/env node
## Usage:
## tmux-window-data sessionName windowName
## Returns:
## - name (with symbol)
## - isZoomed
## - isActive
## - isBeforeActive
## - isAfterActive
(async () => {
  const sessionName = process.argv[2];
  const windowName = process.argv[3];


})();

// #local sessionName="$1"
// #local windowName="$2"

// #local tmuxFormat="active=#{window_active}/name=#{window_name}/index=#{window_index}/zoom=#{window_zoomed_flag}"
// #local rawOutput="$(tmux list-windows -t $sessionName -F "$tmuxFormat")"

// #local rawCurrentWindow

// ## local
// ## echo $rawOutput
// ## # Take the session name
