#!/usr/bin/env zsh
#
# Called with the tab name
# Find all information from there

local output=''
local tmux_path=~/.oroshi/config/tmux
local is_active=$1
local tab_index=$2
local tab_name=$3
local tab_flags=$4
local session_name=$5
local symbol_open=""
local symbol_close=""
local symbol_open_active=""
local symbol_close_active=""
local symbol_zoom="z"

local session_color="$($tmux_path/helper-get-session-color $session_name)"

# Opening tag
local opening_arrow=$symbol_open
[[ $is_active == 1 ]] && opening_arrow="#[fg=colour235,bg=$session_color]$symbol_open_active#[default]"

# Add icon
local tab_icon=" $($tmux_path/helper-get-icon $tab_name)"

# Text color
local fg_color='colour235'
# [[ $session_name == 'algolia' ]] && fg_color='colour249'
# [[ $session_name == 'tmp' ]] && fg_color='colour249'

# # Zoom icon
# local zoom_icon=''
# if [[ $tab_flags == *Z* ]]; then
#   zoom_icon=" $symbol_zoom"
# fi

# Closing tab
local closing_arrow="$symbol_close"
[[ $is_active == 1 ]] && closing_arrow="#[fg=$session_color,bg=colour235]$symbol_close_active#[default]"

# Display name
# local display_name="${tab_icon}${tab_name}${zoom_icon} "
local display_name="${tab_icon}${tab_name} "
if [[ $is_active == 1 ]]; then
  display_name="#[fg=$fg_color,bg=$session_color]${display_name}#[default]"
fi

output="${opening_arrow}${display_name}${closing_arrow}"

echo $output
