#!/usr/bin/env zsh

local output=''
local active=$1
local index=$2
local name=$3
local flags=$4
local session=$5


# Specific color for specific sessions
local session_color='colour136'
[[ $session == 'algolia' ]] && session_color='colour67'
[[ $session == 'perso' ]] && session_color='colour141'
[[ $session == 'projects' ]] && session_color='colour35'


# Add ⮀ if active
if [[ $active == 1 ]]; then
  output="#[fg=colour235,bg=$session_color]⮀"
fi

# Add index and name
output="${output}$index:$name "

# Add few icons for some specific folders
[[ $name == 'blog' ]] && output="$output  "
[[ $name == 'books' ]] && output="$output  "
[[ $name == 'comics' ]] && output="$output  "
[[ $name == 'dropbox' ]] && output="$output  "
[[ $name == 'movies' ]] && output="$output  "
[[ $name == 'music' ]] && output="$output  "
[[ $name == 'oroshi' ]] && output="$output  "
[[ $name == 'roleplay' ]] && output="$output  "
[[ $name == 'twitter' ]] && output="$output  "
[[ $name == 'videos' ]] && output="$output  "

# Add zoomed icon flag if one of the panels is zoomed
if [[ $flags == *Z* ]]; then
  output="${output} "
fi

# Add final coloring
output="$output#[fg=$session_color,bg=colour235]"

# Add ⮁ or ⮀ depending if active
if [[ $active == 1 ]]; then
  output="$output⮀"
else
  output="$output ⮁"
fi

echo $output

