#!/usr/bin/env zsh
# Regenerate ./dist/rgrc.conf from ./src/rgrc.conf

source $ZSH_CONFIG_PATH/theming/env/colors.zsh

local currentDir=${0:a:h}

envsubst \
	<${currentDir}/src/rgrc.conf \
	>${currentDir}/dist/rgrc.conf
