#!/usr/bin/env zsh

local CONFIG_DIR=~/.oroshi/config/vim/nvim
local DEST_DIR=~/.config/nvim

# Create config file
mkdir -p $DEST_DIR
ln \
	-fns $CONFIG_DIR/init.vim \
	$DEST_DIR/init.vim

# Create runtime directories
mkdir -p $DEST_DIR/plugins
mkdir -p $DEST_DIR/swap
mkdir -p $DEST_DIR/undo
mkdir -p $DEST_DIR/view

# Link config directories
ln -fns $CONFIG_DIR/after $DEST_DIR/after
ln -fns $CONFIG_DIR/ftdetect $DEST_DIR/ftdetect
ln -fns $CONFIG_DIR/autoload $DEST_DIR/autoload
ln -fns $CONFIG_DIR/colors $DEST_DIR/colors
ln -fns $CONFIG_DIR/includes $DEST_DIR/includes
ln -fns $CONFIG_DIR/snippets $DEST_DIR/UltiSnips

echo "Now, open nvim and type :PlugUpdate<CR> to install all plugins"
