#!/usr/bin/env zsh

local CONFIG_DIR=~/.oroshi/config/vim/nvim
local DEST_DIR=~/.config/nvim

# Create config file
mkdir -p $DEST_DIR
ln \
	-fns $CONFIG_DIR/init.lua \
	$DEST_DIR/init.lua

# Create config directory
mkdir -p $DEST_DIR/lua
ln -fns $CONFIG_DIR/config $DEST_DIR/lua/oroshi

# Create runtime directories
mkdir -p $DEST_DIR/swap
mkdir -p $DEST_DIR/undo
mkdir -p $DEST_DIR/view
