#!/usr/bin/env zsh
# Image compression and conversion tools
set -e

# Basic image support
sudo apt-get install \
  libimage-exiftool-perl \
  librsvg2-bin

# Conversion
"${0:h}/imagemagick/install"

# Screenshots
"${0:h}/flameshot/install"

# DSSIM
"${0:h}/dssim/install"

# WEBP
"${0:h}/webp/install"

# JPG
"${0:h}/jpegoptim/install"

# PNG
"${0:h}/pngquant/install"

# GIF
"${0:h}/gifsicle/install"
