#!/usr/bin/env bash

# echo "Minifier: CleanCSS"
# node-module-add clean-css-cli

# echo "Linter: Stylelint"
# node-module-add stylelint
# node-module-add stylelint-config-standard
# node-module-add stylelint-scss

# echo "Prettifier: Prettier"
# node-module-add prettier

# echo "Installing Sass"
# gem install sass
# gem install scss_lint

# echo "Installing sass2scss"
# cd ~/local/src
# mkdir -p ./sass2scss
# cd ./sass2scss
# wget https://github.com/mgreter/sass2scss/archive/v1.0.5.tar.gz -O sass2scss.tar.gz
# tar xvf sass2scss.tar.gz
# cd ./sass2scss-1.0.5
# make
# mv ./sass2scss ~/local/bin/sass2scss
