#!/usr/bin/env zsh
# Pytest: Python testing framework
# https://docs.pytest.org
set -e
pipx install pytest

# Add pytest-spec plugin, to display test results in a more readable format
pipx inject pytest pytest-spec
# Add pytest-mock plugin, for cleaner mock syntax via the mocker fixture
pipx inject pytest pytest-mock
